-- MedFacil: esquema mínimo para pruebas (H2)
CREATE TABLE IF NOT EXISTS medication (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    generic_name VARCHAR(255),
    description VARCHAR(4000),
    common_usage VARCHAR(4000),
    precautions VARCHAR(4000),
    dose_guidance VARCHAR(2000),
    side_effects VARCHAR(4000)
);

CREATE TABLE IF NOT EXISTS quiz_question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt VARCHAR(2000) NOT NULL,
    explanation VARCHAR(4000)
);

CREATE TABLE IF NOT EXISTS quiz_option (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    option_text VARCHAR(1000) NOT NULL,
    correct BOOLEAN NOT NULL,
    CONSTRAINT fk_quiz_option_question FOREIGN KEY (question_id) REFERENCES quiz_question(id)
);
