spring.application.name=pharmly
server.port=${PORT:8080}

# UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.force-request=true
server.servlet.encoding.force-response=true
server.tomcat.uri-encoding=UTF-8

spring.web.resources.static-locations=classpath:/static/

# --- Base de datos PostgreSQL (variables de entorno que provee Render) ---
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

# Scripts SQL al iniciar
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# JPA con PostgreSQL
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# H2 desactivado
spring.h2.console.enabled=false

spring.datasource.hikari.maximum-pool-size=5

# Groq
groq.api.key=${GROQ_API_KEY:}
