-- ============================================================
-- PHARMLY: datos iniciales (H2 en memoria)
-- ============================================================

-- ===== Usuarios (login) =====
INSERT INTO usuario (nombre_usuario, contrasenia, tipo, nombre, correo) VALUES
('admin', 'admin123', 'ADMIN', 'Administrador del Sistema', 'admin@pharmly.pe'),
('estudiante', 'estudiante123', 'ESTUDIANTE', 'Estudiante de Farmacologia', 'estudiante@pharmly.pe'),
('usuario', 'usuario123', 'USUARIO_GENERAL', 'Usuario General', 'usuario@pharmly.pe');
ON CONFLICT (nombre_usuario) DO NOTHING;

-- ===== Categorías de medicamentos =====
INSERT INTO categoria_medicamento (clave, nombre) VALUES
('analgesicos', 'Analgésicos'),
('antiinflamatorios', 'Antiinflamatorios'),
('antibioticos', 'Antibióticos'),
('cardiovasculares', 'Cardiovasculares'),
('neurologicos', 'Neurológicos'),
('dermatologicos', 'Dermatológicos'),
('antialergicos', 'Antialérgicos'),
('gastrointestinales', 'Gastrointestinales'),
('endocrinos', 'Endocrinos'),
('respiratorios', 'Respiratorios'),
('suplementos', 'Suplementos y vitaminas');
ON CONFLICT (nombre_usuario) DO NOTHING;

-- ===== Categorías de dolencias =====
INSERT INTO categoria_dolencia (id, nombre) VALUES
(1, 'Respiratorias'),
(2, 'Digestivas'),
(3, 'Neurológicas'),
(4, 'Cardiovasculares'),
(5, 'Metabólicas'),
(6, 'Alérgicas y dermatológicas'),
(7, 'Osteomusculares'),
(8, 'Otras');
ON CONFLICT (nombre_usuario) DO NOTHING;

-- ===== Dolencias (significado, síntomas y consejos para la búsqueda) =====
INSERT INTO dolencia (nombre, categoria_id, descripcion, sintomas, consejos) VALUES
('Gripe', 1,
 'Infección viral de las vías respiratorias causada por el virus de la influenza. No se trata con antibióticos.',
 'Fiebre, dolor de cuerpo, congestión nasal, tos, dolor de garganta y malestar general.',
 'Reposo, abundante hidratación y antitérmicos como paracetamol según prospecto. Consulta si la fiebre dura más de 3 días o hay dificultad para respirar.'),
('Asma', 1,
 'Enfermedad crónica que inflama y estrecha las vías respiratorias dificultando el paso del aire.',
 'Silbidos al respirar, tos seca (sobre todo nocturna), sensación de pecho apretado y falta de aire.',
 'Evita los desencadenantes (polvo, humo, ejercicio intenso sin calentar). Usa el inhalador de rescate (salbutamol) según indicación y acude a control médico periódico.'),
('Bronquitis', 1,
 'Inflamación de los bronquios, generalmente de origen viral.',
 'Tos persistente con o sin flema, molestia en el pecho y cansancio.',
 'Hidratación, reposo y evitar el humo del tabaco. Consulta si hay fiebre alta, dificultad respiratoria o la tos dura más de 3 semanas.'),
('Faringitis', 1,
 'Inflamación de la faringe (garganta), de origen viral en la mayoría de casos.',
 'Dolor de garganta al tragar, enrojecimiento, fiebre y a veces ganglios inflamados en el cuello.',
 'Líquidos tibios, gárgaras de agua con sal y analgésicos suaves. Si hay placas de pus o fiebre alta persistente, el médico evaluará si necesita antibiótico.'),
('Gastritis', 2,
 'Inflamación de la mucosa que recubre el estómago.',
 'Ardor o dolor en la boca del estómago, náuseas, sensación de llenura y acidez.',
 'Evita ayunos prolongados, picantes, alcohol y AINE sin protección. El omeprazol puede aliviar bajo indicación; si persiste, consulta para descartar H. pylori.'),
('Reflujo gastroesofágico', 2,
 'Retorno del contenido ácido del estómago hacia el esófago.',
 'Acidez o agruras que empeoran al acostarse, regurgitación y a veces tos nocturna.',
 'Cena ligero y al menos 2 horas antes de dormir, eleva la cabecera de la cama y evita café, alcohol y comidas muy grasosas.'),
('Diarrea aguda', 2,
 'Aumento de deposiciones líquidas, generalmente por infecciones o alimentos contaminados.',
 'Deposiciones líquidas frecuentes, cólicos, a veces náuseas; el mayor riesgo es la deshidratación.',
 'Toma sales de rehidratación oral, continúa alimentándote con dieta blanda y lávate las manos. Acude al médico si hay sangre, fiebre alta o dura más de 2 días.'),
('Migraña', 3,
 'Dolor de cabeza intenso y pulsátil, muchas veces en un solo lado de la cabeza.',
 'Dolor pulsátil, náuseas, molestia ante la luz (fotofobia) y el ruido; puede durar horas.',
 'Descansa en un lugar oscuro y silencioso, identifica tus desencadenantes (estrés, ciertos alimentos, falta de sueño) y usa el analgésico indicado al inicio del dolor.'),
('Epilepsia', 3,
 'Trastorno neurológico con crisis convulsivas recurrentes.',
 'Crisis convulsivas, episodios de desconexión o movimientos involuntarios repetidos.',
 'Requiere control por neurología y tomar la medicación (p. ej. carbamazepina) todos los días sin suspenderla de golpe. Durante una crisis: proteger la cabeza y no introducir objetos en la boca.'),
('Hipertensión arterial', 4,
 'Elevación sostenida de la presión arterial por encima de 140/90 mmHg.',
 'Generalmente no produce síntomas; por eso se le llama el enemigo silencioso.',
 'Reduce la sal, mantén un peso saludable, haz ejercicio y toma tu medicación (p. ej. losartán o enalapril) todos los días. Controla tu presión con regularidad.'),
('Diabetes tipo 2', 5,
 'Niveles elevados de glucosa en sangre por resistencia a la insulina.',
 'Sed excesiva, orinar con frecuencia, cansancio y a veces visión borrosa; puede ser silenciosa.',
 'Dieta saludable, ejercicio regular y medicación como la metformina según indicación. Controla tu glucosa y revisa tus pies con frecuencia.'),
('Anemia ferropénica', 5,
 'Disminución de hemoglobina por falta de hierro.',
 'Cansancio, palidez, uñas frágiles, mareos y dificultad para concentrarse.',
 'Consume alimentos ricos en hierro (carnes rojas, menestras, sangrecita) y toma el suplemento de hierro indicado, idealmente con vitamina C para absorberlo mejor.'),
('Rinitis alérgica', 6,
 'Reacción alérgica de la mucosa nasal frente a polvo, polen u otros alérgenos.',
 'Estornudos en salva, picazón nasal y de ojos, congestión y secreción acuosa.',
 'Evita el alérgeno (ventila y limpia el polvo con paño húmedo), y usa antihistamínicos como loratadina o cetirizina según prospecto.'),
('Dermatitis', 6,
 'Inflamación de la piel de causa irritativa o alérgica.',
 'Enrojecimiento, picazón, descamación y a veces pequeñas ampollas.',
 'Usa jabones suaves, hidrata la piel a diario y evita rascarte. La crema de hidrocortisona puede ayudar en brotes leves, por pocos días.'),
('Lumbalgia', 7,
 'Dolor en la zona baja de la espalda, casi siempre de origen muscular.',
 'Dolor lumbar que aumenta con movimientos o malas posturas; puede irradiarse al glúteo.',
 'Mantente activo con movimientos suaves, aplica calor local y cuida tu postura. Si el dolor baja por la pierna o hay hormigueo, consulta al médico.'),
('Artritis', 7,
 'Inflamación de las articulaciones.',
 'Dolor, hinchazón y rigidez articular, sobre todo al levantarse por la mañana.',
 'Ejercicio de bajo impacto, control del peso y antiinflamatorios según indicación. El reumatólogo definirá el tratamiento de fondo.'),
('Otitis', 8,
 'Inflamación o infección del oído, frecuente en niños.',
 'Dolor de oído, sensación de oído tapado, a veces fiebre o secreción.',
 'No introduzcas hisopos ni gotas sin indicación. El médico decidirá si requiere antibiótico; el paracetamol ayuda con el dolor.'),
('Conjuntivitis', 8,
 'Inflamación de la conjuntiva del ojo, de causa viral, bacteriana o alérgica.',
 'Ojo rojo, lagrimeo, ardor, secreción y sensación de arenilla.',
 'Lava con agua hervida fría, no compartas toallas y evita tocarte los ojos. Si hay dolor intenso o baja la visión, acude de inmediato.'),
('Insomnio', 8,
 'Dificultad para conciliar o mantener el sueño.',
 'Demora en quedarse dormido, despertares frecuentes y cansancio durante el día.',
 'Mantén horarios fijos, evita pantallas y cafeína por la noche, y usa la cama solo para dormir. No tomes pastillas para dormir sin indicación médica.'),
('Estreñimiento', 8,
 'Dificultad o baja frecuencia para evacuar el intestino.',
 'Deposiciones duras, esfuerzo al evacuar y sensación de evacuación incompleta.',
 'Aumenta fibra (frutas, verduras, avena), toma más agua y haz ejercicio. Los laxantes solo de forma ocasional y según indicación.');
ON CONFLICT (nombre_usuario) DO NOTHING;

-- ===== Medicamentos (ficha detallada) =====
INSERT INTO medicamento (
    nombre, nombre_generico, descripcion, uso_comun, precauciones, orientacion_dosis, efectos_secundarios,
    contraindicaciones, interacciones, via_administracion, requiere_receta, categoria, presentacion, precio
) VALUES
('Paracetamol', 'acetaminofén',
 'Analgésico y antipirético de venta común.',
 'Dolor leve a moderado o fiebre, según indicación médica o prospecto.',
 'No exceder la dosis; consultar si hay enfermedad hepática o consumo de alcohol.',
 'Adultos: habitualmente 500 mg a 1 g cada 6-8 horas, sin superar 4 g al día. Respetar siempre el prospecto.',
 'En dosis habituales suele ser bien tolerado; reacciones alérgicas son poco frecuentes.',
 'Enfermedad hepática grave; alergia al paracetamol.',
 'Alcohol (aumenta riesgo hepático), warfarina y otros productos que también contengan paracetamol.',
 'Oral', FALSE, 'analgesicos', 'Comprimidos 500 mg', 8.50),

('Ibuprofeno', 'ibuprofeno',
 'Antiinflamatorio no esteroideo (AINE).',
 'Dolor inflamatorio leve, fiebre y molestias musculares, según indicación.',
 'Tomar con alimento; evitar si hay úlcera activa o problemas renales sin supervisión médica.',
 'Adultos: habitualmente 400 mg cada 8 horas. Usar la menor dosis efectiva por el menor tiempo posible.',
 'Puede causar molestias digestivas; otros efectos son menos frecuentes.',
 'Úlcera gastroduodenal activa, insuficiencia renal grave, tercer trimestre del embarazo.',
 'Anticoagulantes, corticoides, antihipertensivos y otros AINE.',
 'Oral', FALSE, 'antiinflamatorios', 'Comprimidos 400 mg', 12.90),

('Amoxicilina', 'amoxicilina',
 'Antibiótico betalactámico de amplio espectro.',
 'Infecciones bacterianas según prescripción; completar el tratamiento indicado.',
 'No usar sin indicación médica; informar alergia a penicilinas.',
 'Dosis y duración según criterio profesional y peso/edad del paciente.',
 'Diarrea leve, náuseas o erupciones cutáneas; ante reacción grave suspender y acudir a urgencias.',
 'Alergia a penicilinas o cefalosporinas.',
 'Puede reducir la eficacia de anticonceptivos orales; interacción con alopurinol y metotrexato.',
 'Oral', TRUE, 'antibioticos', 'Cápsulas 500 mg', 24.00),

('Losartán', 'losartán',
 'Antihipertensivo (bloqueante del receptor de angiotensina II).',
 'Hipertensión arterial según pauta médica.',
 'Controlar función renal y potasio; informar embarazo o lactancia.',
 'Habitualmente 50 mg una vez al día; no modificar la dosis sin supervisión.',
 'Mareo leve, fatiga o elevación de potasio en sangre son posibles.',
 'Embarazo, hiperpotasemia, alergia al principio activo.',
 'Diuréticos ahorradores de potasio, suplementos de potasio y AINE.',
 'Oral', TRUE, 'cardiovasculares', 'Comprimidos 50 mg', 18.75),

('Carbamazepina', 'carbamazepina',
 'Antiepiléptico también usado en neuralgia del trigémino.',
 'Epilepsia o dolor neuropático solo con indicación especializada.',
 'Requiere controles de sangre; interacciones múltiples con otros fármacos.',
 'Ajuste gradual según respuesta y tolerancia; no interrumpir de golpe.',
 'Somnolencia, visión borrosa o reacciones cutáneas graves (poco frecuentes) requieren valoración urgente.',
 'Bloqueo auriculoventricular, antecedentes de depresión de médula ósea.',
 'Anticonceptivos orales, warfarina y otros antiepilépticos; reduce el efecto de varios fármacos.',
 'Oral', TRUE, 'neurologicos', 'Comprimidos 200 mg', 35.20),

('Loratadina', 'loratadina',
 'Antihistamínico de segunda generación.',
 'Rinitis alérgica o urticaria según prospecto o indicación.',
 'Precaución en insuficiencia hepática grave; consultar interacciones.',
 'Adultos: habitualmente 10 mg una vez al día; no duplicar con otros antihistamínicos.',
 'Somnolencia leve o sequedad de boca en algunas personas.',
 'Alergia a la loratadina.',
 'Ketoconazol y eritromicina pueden aumentar sus niveles en sangre.',
 'Oral', FALSE, 'antialergicos', 'Jarabe 5 mg / 5 ml', 15.40),

('Omeprazol', 'omeprazol',
 'Inhibidor de la bomba de protones; reduce la producción de ácido gástrico.',
 'Acidez, gastritis y reflujo gastroesofágico según indicación.',
 'No usar de forma prolongada sin control médico.',
 'Habitualmente 20 mg una vez al día antes del desayuno.',
 'Dolor de cabeza, náuseas o diarrea leve en algunas personas.',
 'Alergia al omeprazol u otros inhibidores de la bomba de protones.',
 'Clopidogrel (puede reducir su efecto), ketoconazol y hierro oral.',
 'Oral', FALSE, 'gastrointestinales', 'Cápsulas 20 mg', 14.60),

('Metformina', 'metformina',
 'Antidiabético oral de primera línea para diabetes tipo 2.',
 'Control de la glucosa en diabetes tipo 2, junto con dieta y ejercicio.',
 'Controlar función renal; suspender ante procedimientos con contraste yodado según indicación.',
 'Inicio habitual 500-850 mg con las comidas; ajuste progresivo según tolerancia.',
 'Molestias digestivas al inicio (náuseas, diarrea); suelen disminuir con el tiempo.',
 'Insuficiencia renal grave, acidosis metabólica.',
 'Alcohol en exceso y medios de contraste yodados aumentan el riesgo de acidosis láctica.',
 'Oral', TRUE, 'endocrinos', 'Comprimidos 850 mg', 16.30),

('Salbutamol', 'salbutamol',
 'Broncodilatador de acción rápida (agonista beta-2).',
 'Alivio rápido de crisis de asma o broncoespasmo.',
 'Si se necesita con mucha frecuencia, el asma puede estar mal controlada: consultar.',
 'Inhalación según necesidad e indicación; respetar el número máximo de aplicaciones del prospecto.',
 'Temblor fino, palpitaciones o nerviosismo transitorios.',
 'Alergia al salbutamol.',
 'Betabloqueantes pueden reducir su efecto; precaución con otros estimulantes.',
 'Inhalatoria', TRUE, 'respiratorios', 'Inhalador 100 mcg/dosis', 28.90),

('Aspirina', 'ácido acetilsalicílico',
 'Analgésico, antipirético y antiagregante plaquetario.',
 'Dolor leve, fiebre y, en dosis bajas, prevención cardiovascular bajo indicación médica.',
 'No usar en menores con infecciones virales (riesgo de síndrome de Reye); precaución con problemas gástricos.',
 'Según uso: dolor/fiebre en adultos 500 mg cada 6-8 horas; prevención cardiovascular en dosis bajas indicadas por el médico.',
 'Molestias gástricas y mayor tendencia al sangrado.',
 'Úlcera activa, trastornos de coagulación, menores de 16 años con cuadros virales.',
 'Anticoagulantes, otros AINE y corticoides aumentan el riesgo de sangrado digestivo.',
 'Oral', FALSE, 'analgesicos', 'Comprimidos 500 mg', 9.80);
ON CONFLICT (nombre_usuario) DO NOTHING;

INSERT INTO medicamento (
    nombre, nombre_generico, descripcion, uso_comun, precauciones, orientacion_dosis, efectos_secundarios,
    contraindicaciones, interacciones, via_administracion, requiere_receta, categoria, presentacion, precio
) VALUES
('Naproxeno', 'naproxeno',
 'Antiinflamatorio no esteroideo (AINE) de acción prolongada.',
 'Dolor muscular, articular, menstrual e inflamación.',
 'Tomar con alimentos; evitar uso prolongado sin control médico.',
 'Adultos: habitualmente 250-500 mg cada 12 horas según prospecto.',
 'Molestias gástricas, mareo o somnolencia leve.',
 'Úlcera activa, insuficiencia renal grave, tercer trimestre del embarazo.',
 'Anticoagulantes, otros AINE, antihipertensivos.',
 'Oral', FALSE, 'antiinflamatorios', 'Comprimidos 550 mg', 13.50),

('Cetirizina', 'cetirizina',
 'Antihistamínico de segunda generación.',
 'Rinitis alérgica, urticaria y picazón por alergias.',
 'Puede causar algo de somnolencia; precaución al conducir.',
 'Adultos: 10 mg una vez al día según prospecto.',
 'Somnolencia leve, sequedad de boca.',
 'Alergia a la cetirizina o hidroxizina; insuficiencia renal grave sin ajuste.',
 'El alcohol y sedantes potencian la somnolencia.',
 'Oral', FALSE, 'antialergicos', 'Comprimidos 10 mg', 12.00),

('Azitromicina', 'azitromicina',
 'Antibiótico macrólido de amplio espectro.',
 'Infecciones respiratorias, de garganta y de piel según prescripción.',
 'Solo con indicación médica; completar el esquema aunque mejoren los síntomas.',
 'Esquema habitual: una toma diaria por 3-5 días según indicación.',
 'Molestias digestivas, diarrea leve.',
 'Alergia a macrólidos; antecedentes de arritmias (QT prolongado).',
 'Antiácidos con aluminio/magnesio reducen su absorción; precaución con otros fármacos que prolongan el QT.',
 'Oral', TRUE, 'antibioticos', 'Tabletas 500 mg', 19.90),

('Ciprofloxacino', 'ciprofloxacino',
 'Antibiótico de la familia de las fluoroquinolonas.',
 'Infecciones urinarias y digestivas según prescripción.',
 'Evitar exposición solar intensa; hidratarse bien; no usar en niños salvo indicación.',
 'Según prescripción; habitualmente cada 12 horas por el tiempo indicado.',
 'Náuseas, diarrea; raramente dolor de tendones (suspender y consultar).',
 'Alergia a quinolonas, embarazo y lactancia salvo indicación, menores de edad en general.',
 'Lácteos y antiácidos reducen su absorción; potencia el efecto de la warfarina.',
 'Oral', TRUE, 'antibioticos', 'Tabletas 500 mg', 16.80),

('Enalapril', 'enalapril',
 'Antihipertensivo inhibidor de la ECA (IECA).',
 'Hipertensión arterial e insuficiencia cardiaca según indicación.',
 'Controlar función renal y potasio; puede producir tos seca persistente.',
 'Habitualmente 10-20 mg al día según control de presión.',
 'Tos seca, mareo al inicio del tratamiento.',
 'Embarazo, antecedente de angioedema, hiperpotasemia.',
 'AINE reducen su efecto; diuréticos ahorradores de potasio aumentan el potasio.',
 'Oral', TRUE, 'cardiovasculares', 'Comprimidos 10 mg', 11.40),

('Amlodipino', 'amlodipino',
 'Antihipertensivo bloqueador de canales de calcio.',
 'Hipertensión arterial y angina estable.',
 'No suspender bruscamente; informar hinchazón de tobillos.',
 'Habitualmente 5-10 mg una vez al día.',
 'Hinchazón de tobillos, enrojecimiento facial, dolor de cabeza.',
 'Hipotensión severa, alergia al principio activo.',
 'Jugo de toronja puede aumentar sus niveles; precaución con otros antihipertensivos.',
 'Oral', TRUE, 'cardiovasculares', 'Comprimidos 5 mg', 14.20),

('Atorvastatina', 'atorvastatina',
 'Estatina que reduce el colesterol en sangre.',
 'Colesterol elevado y prevención cardiovascular según indicación.',
 'Informar dolores musculares intensos; control periódico de enzimas hepáticas.',
 'Habitualmente 10-40 mg una vez al día, de preferencia en la noche.',
 'Dolores musculares leves, molestias digestivas.',
 'Enfermedad hepática activa, embarazo y lactancia.',
 'Jugo de toronja y ciertos antibióticos aumentan el riesgo de daño muscular.',
 'Oral', TRUE, 'cardiovasculares', 'Tabletas 20 mg', 22.50),

('Famotidina', 'famotidina',
 'Antiácido bloqueador H2; reduce la producción de ácido gástrico.',
 'Acidez, gastritis leve y úlcera según indicación.',
 'Si los síntomas persisten más de 2 semanas, consultar.',
 'Habitualmente 20-40 mg al día según prospecto.',
 'Dolor de cabeza, estreñimiento o diarrea leves.',
 'Alergia a la famotidina; insuficiencia renal grave sin ajuste de dosis.',
 'Puede reducir la absorción de medicamentos que requieren acidez (p. ej. ketoconazol).',
 'Oral', FALSE, 'gastrointestinales', 'Tabletas 20 mg', 9.60),

('Lansoprazol', 'lansoprazol',
 'Inhibidor de la bomba de protones.',
 'Reflujo gastroesofágico, gastritis y protección gástrica según indicación.',
 'Uso prolongado solo con control médico.',
 'Habitualmente 30 mg una vez al día antes del desayuno.',
 'Dolor de cabeza, náuseas, diarrea leve.',
 'Alergia a inhibidores de bomba de protones.',
 'Reduce la absorción de hierro y de algunos antimicóticos.',
 'Oral', FALSE, 'gastrointestinales', 'Cápsulas 30 mg', 15.80),

('Diazepam', 'diazepam',
 'Benzodiacepina con efecto ansiolítico, sedante y relajante muscular.',
 'Ansiedad severa, espasmos musculares y ciertas crisis, solo bajo prescripción.',
 'Produce dependencia: uso por el menor tiempo posible y nunca con alcohol.',
 'Dosis estrictamente individualizada por el médico.',
 'Somnolencia, mareo, disminución de reflejos.',
 'Apnea del sueño, insuficiencia respiratoria grave, embarazo, antecedentes de adicción.',
 'Alcohol, opioides y otros sedantes potencian la depresión respiratoria.',
 'Oral', TRUE, 'neurologicos', 'Tabletas 10 mg', 8.90),

('Prednisona', 'prednisona',
 'Corticoide sistémico con potente efecto antiinflamatorio.',
 'Alergias severas, asma, enfermedades autoinmunes según prescripción.',
 'No suspender de golpe en tratamientos largos; tomar con alimentos.',
 'Dosis y descenso gradual definidos por el médico.',
 'Aumento de apetito, insomnio, retención de líquidos; en uso prolongado más efectos.',
 'Infecciones activas no tratadas, úlcera péptica activa.',
 'AINE aumentan riesgo gástrico; reduce el efecto de vacunas de virus vivos.',
 'Oral', TRUE, 'antiinflamatorios', 'Tabletas 20 mg', 10.70),

('Hidrocortisona crema', 'hidrocortisona',
 'Corticoide tópico de baja potencia.',
 'Dermatitis, picaduras e irritaciones leves de la piel.',
 'No usar en heridas abiertas ni por más de 7 días seguidos sin indicación.',
 'Capa fina sobre la zona afectada 1-2 veces al día.',
 'Ardor leve al aplicar; uso prolongado puede adelgazar la piel.',
 'Infecciones de piel por hongos o bacterias sin tratamiento.',
 'Pocas interacciones por vía tópica.',
 'Tópica', FALSE, 'dermatologicos', 'Crema 1% x 15 g', 7.50),

('Clotrimazol', 'clotrimazol',
 'Antimicótico tópico.',
 'Hongos de la piel y pie de atleta.',
 'Completar el tratamiento aunque mejore antes; mantener la zona seca.',
 'Aplicar 2-3 veces al día por 2-4 semanas según prospecto.',
 'Irritación o ardor local leve.',
 'Alergia al clotrimazol.',
 'Pocas interacciones por vía tópica.',
 'Tópica', FALSE, 'dermatologicos', 'Crema 1% x 20 g', 8.20),

('Metamizol', 'metamizol sódico',
 'Analgésico y antipirético no opioide.',
 'Dolor moderado y fiebre que no cede con otras medidas, bajo indicación.',
 'Usar bajo indicación; suspender ante fiebre con dolor de garganta inexplicado.',
 'Según indicación médica; no exceder la dosis del prospecto.',
 'Hipotensión si se administra muy rápido; raramente afecta los glóbulos blancos.',
 'Alergia a pirazolonas, antecedentes de agranulocitosis.',
 'Precaución con otros depresores de médula ósea.',
 'Oral', TRUE, 'analgesicos', 'Tabletas 500 mg', 6.90),

('Sulfato ferroso', 'hierro elemental',
 'Suplemento de hierro para la anemia ferropénica.',
 'Tratamiento y prevención de la anemia por falta de hierro.',
 'Tomar lejos de lácteos y café; puede oscurecer las deposiciones (normal).',
 'Según indicación; idealmente en ayunas o con jugo de naranja (vitamina C).',
 'Estreñimiento, náuseas, deposiciones oscuras.',
 'Hemocromatosis y otras sobrecargas de hierro.',
 'Antiácidos, calcio y té reducen su absorción.',
 'Oral', FALSE, 'suplementos', 'Tabletas 300 mg', 5.40),

('Ácido fólico', 'ácido fólico',
 'Vitamina B9, esencial para la formación de células.',
 'Prevención de defectos del tubo neural en el embarazo y ciertas anemias.',
 'En embarazo, iniciar idealmente antes de la concepción.',
 'Habitualmente 0.4-1 mg al día según indicación.',
 'Muy bien tolerado en dosis habituales.',
 'Alergia al ácido fólico.',
 'Algunos antiepilépticos reducen sus niveles.',
 'Oral', FALSE, 'suplementos', 'Tabletas 0.5 mg', 4.80),

('Vitamina C', 'ácido ascórbico',
 'Vitamina antioxidante que participa en la inmunidad y absorción del hierro.',
 'Apoyo en resfriados y mejora de la absorción de hierro.',
 'Dosis muy altas pueden causar molestias digestivas o cálculos renales.',
 'Habitualmente 500 mg a 1 g al día según prospecto.',
 'Molestias digestivas leves en dosis altas.',
 'Antecedentes de cálculos renales por oxalato (dosis altas).',
 'Mejora la absorción del hierro; pocas interacciones relevantes.',
 'Oral', FALSE, 'suplementos', 'Tabletas masticables 500 mg', 6.20);
ON CONFLICT (nombre_usuario) DO NOTHING;

-- ===== Más medicamentos (mismas categorías) =====
INSERT INTO medicamento (
    nombre, nombre_generico, descripcion, uso_comun, precauciones, orientacion_dosis, efectos_secundarios,
    contraindicaciones, interacciones, via_administracion, requiere_receta, categoria, presentacion, precio
) VALUES
-- Analgésicos
('Tramadol', 'tramadol',
 'Analgésico opioide de potencia moderada.',
 'Dolor moderado a severo que no cede con analgésicos comunes, bajo prescripción.',
 'Puede causar dependencia; no combinar con alcohol ni conducir al inicio.',
 'Dosis individualizada por el médico; no exceder 400 mg al día.',
 'Náuseas, mareo, somnolencia, estreñimiento.',
 'Epilepsia no controlada, intoxicación por alcohol o sedantes.',
 'Antidepresivos (riesgo de síndrome serotoninérgico), sedantes y alcohol.',
 'Oral', TRUE, 'analgesicos', 'Cápsulas 50 mg', 12.40),

('Ketorolaco', 'ketorolaco',
 'Analgésico AINE de alta potencia para uso a corto plazo.',
 'Dolor agudo moderado a severo (postoperatorio, cólicos), máximo 5 días.',
 'Solo por pocos días; alto riesgo gástrico y renal en uso prolongado.',
 'Según prescripción; habitualmente 10 mg cada 6-8 horas, máximo 5 días.',
 'Ardor estomacal, náuseas, mareo.',
 'Úlcera activa, sangrado digestivo, insuficiencia renal, embarazo.',
 'Otros AINE, anticoagulantes y corticoides aumentan el riesgo de sangrado.',
 'Oral', TRUE, 'analgesicos', 'Tabletas 10 mg', 9.30),

-- Antiinflamatorios
('Diclofenaco', 'diclofenaco sódico',
 'Antiinflamatorio no esteroideo de uso muy extendido.',
 'Dolor e inflamación muscular, articular y dental.',
 'Tomar con alimentos; evitar en problemas cardiacos sin evaluación.',
 'Adultos: habitualmente 50 mg cada 8-12 horas según prospecto.',
 'Molestias gástricas, dolor de cabeza, elevación de presión.',
 'Úlcera péptica, insuficiencia cardiaca grave, tercer trimestre del embarazo.',
 'Anticoagulantes, antihipertensivos, otros AINE.',
 'Oral', FALSE, 'antiinflamatorios', 'Tabletas 50 mg', 8.70),

('Meloxicam', 'meloxicam',
 'AINE con mayor selectividad y menos molestias gástricas.',
 'Artritis, artrosis y dolores articulares crónicos.',
 'Usar la menor dosis efectiva; controlar presión arterial.',
 'Habitualmente 7.5-15 mg una vez al día.',
 'Molestias digestivas leves, mareo, hinchazón de tobillos.',
 'Úlcera activa, insuficiencia renal grave, embarazo.',
 'Anticoagulantes, litio, otros AINE.',
 'Oral', TRUE, 'antiinflamatorios', 'Tabletas 15 mg', 11.20),

('Dexametasona', 'dexametasona',
 'Corticoide potente de acción prolongada.',
 'Alergias severas, inflamación intensa y ciertos tratamientos hospitalarios.',
 'Solo bajo indicación; en tratamientos largos no suspender de golpe.',
 'Dosis y duración estrictamente definidas por el médico.',
 'Insomnio, aumento de apetito, retención de líquidos, elevación de glucosa.',
 'Infecciones sistémicas no tratadas, alergia al principio activo.',
 'AINE (riesgo gástrico), antidiabéticos (sube la glucosa), vacunas de virus vivos.',
 'Oral', TRUE, 'antiinflamatorios', 'Tabletas 4 mg', 7.90),

-- Antibióticos
('Cefalexina', 'cefalexina',
 'Antibiótico betalactámico de la familia de las cefalosporinas.',
 'Infecciones de piel, garganta y vías urinarias según prescripción.',
 'Informar si hay alergia a penicilinas; completar todo el esquema.',
 'Según prescripción; habitualmente 500 mg cada 6-8 horas.',
 'Diarrea leve, náuseas, erupción cutánea.',
 'Alergia a cefalosporinas o reacción grave previa a penicilinas.',
 'Probenecid aumenta sus niveles; puede potenciar anticoagulantes.',
 'Oral', TRUE, 'antibioticos', 'Cápsulas 500 mg', 15.60),

('Doxiciclina', 'doxiciclina',
 'Antibiótico de la familia de las tetraciclinas.',
 'Acné severo, infecciones respiratorias y algunas zoonosis según prescripción.',
 'Evitar el sol intenso (fotosensibilidad); tomar con abundante agua y sin acostarse de inmediato.',
 'Según prescripción; habitualmente 100 mg cada 12-24 horas.',
 'Molestias digestivas, fotosensibilidad.',
 'Embarazo, lactancia y menores de 8 años (mancha los dientes).',
 'Lácteos, antiácidos y hierro reducen su absorción.',
 'Oral', TRUE, 'antibioticos', 'Tabletas 100 mg', 13.80),

('Clindamicina', 'clindamicina',
 'Antibiótico lincosamida útil en infecciones de piel y dentales.',
 'Infecciones dentales, de piel y huesos según prescripción.',
 'Suspender y consultar si aparece diarrea intensa (riesgo de colitis).',
 'Según prescripción; habitualmente 300 mg cada 6-8 horas.',
 'Diarrea, náuseas, sabor metálico.',
 'Antecedente de colitis asociada a antibióticos.',
 'Puede antagonizar con eritromicina; potencia relajantes musculares.',
 'Oral', TRUE, 'antibioticos', 'Cápsulas 300 mg', 18.40),

('Metronidazol', 'metronidazol',
 'Antibiótico y antiparasitario para infecciones por anaerobios y protozoos.',
 'Infecciones intestinales, vaginales y dentales según prescripción.',
 'No consumir alcohol durante el tratamiento ni 48 horas después (reacción severa).',
 'Según prescripción; habitualmente 500 mg cada 8 horas.',
 'Sabor metálico, náuseas, orina oscura.',
 'Primer trimestre del embarazo salvo indicación; alergia al principio activo.',
 'Alcohol (efecto antabus), warfarina (potencia su efecto), litio.',
 'Oral', TRUE, 'antibioticos', 'Tabletas 500 mg', 9.90),

('Nitrofurantoína', 'nitrofurantoína',
 'Antibiótico específico para infecciones urinarias bajas.',
 'Cistitis e infecciones urinarias no complicadas según prescripción.',
 'Tomar con alimentos; puede teñir la orina de color amarillo oscuro.',
 'Según prescripción; habitualmente 100 mg cada 6-12 horas.',
 'Náuseas, dolor de cabeza, orina oscura.',
 'Insuficiencia renal significativa, último mes de embarazo.',
 'Antiácidos con magnesio reducen su absorción.',
 'Oral', TRUE, 'antibioticos', 'Cápsulas 100 mg', 12.60),

-- Cardiovasculares
('Metoprolol', 'metoprolol',
 'Betabloqueador que reduce la frecuencia cardiaca y la presión.',
 'Hipertensión, angina y control del ritmo cardiaco.',
 'No suspender bruscamente; controlar pulso (avisar si baja de 50).',
 'Habitualmente 50-100 mg al día según indicación.',
 'Cansancio, manos frías, pulso lento, mareo.',
 'Asma severa, bloqueos cardiacos, bradicardia importante.',
 'Otros antihipertensivos, antiarrítmicos; enmascara hipoglucemias en diabéticos.',
 'Oral', TRUE, 'cardiovasculares', 'Tabletas 50 mg', 10.90),

('Furosemida', 'furosemida',
 'Diurético de asa potente.',
 'Retención de líquidos por insuficiencia cardiaca, renal o hepática.',
 'Controlar potasio y presión; tomar por la mañana para evitar levantarse de noche.',
 'Según prescripción; habitualmente 20-40 mg al día.',
 'Orinar frecuente, calambres, mareo por presión baja.',
 'Deshidratación severa, hipokalemia no corregida, anuria.',
 'Digoxina (riesgo si baja el potasio), AINE reducen su efecto, aminoglucósidos.',
 'Oral', TRUE, 'cardiovasculares', 'Tabletas 40 mg', 6.50),

('Hidroclorotiazida', 'hidroclorotiazida',
 'Diurético tiazídico de primera línea en hipertensión.',
 'Hipertensión arterial y edemas leves.',
 'Controlar potasio y glucosa; protegerse del sol.',
 'Habitualmente 12.5-25 mg una vez al día por la mañana.',
 'Orinar frecuente, calambres, mareo.',
 'Gota severa, alergia a sulfas, insuficiencia renal avanzada.',
 'Litio (aumenta sus niveles), AINE reducen su efecto.',
 'Oral', TRUE, 'cardiovasculares', 'Tabletas 25 mg', 5.80),

('Clopidogrel', 'clopidogrel',
 'Antiagregante plaquetario que previene trombos.',
 'Prevención de infartos y trombosis en pacientes de riesgo.',
 'Avisar a médicos y dentistas antes de procedimientos; no suspender por cuenta propia.',
 'Habitualmente 75 mg una vez al día.',
 'Moretones con facilidad, sangrados menores.',
 'Sangrado activo (úlcera, hemorragia cerebral).',
 'AINE y anticoagulantes aumentan el riesgo de sangrado; omeprazol puede reducir su efecto.',
 'Oral', TRUE, 'cardiovasculares', 'Tabletas 75 mg', 19.50),

-- Neurológicos
('Sertralina', 'sertralina',
 'Antidepresivo inhibidor selectivo de la recaptación de serotonina (ISRS).',
 'Depresión y trastornos de ansiedad bajo control médico.',
 'El efecto completo tarda 2-4 semanas; no suspender de golpe.',
 'Habitualmente 50-100 mg una vez al día.',
 'Náuseas al inicio, insomnio o somnolencia, cambios de apetito.',
 'Uso junto con IMAO; alergia al principio activo.',
 'Otros serotoninérgicos (tramadol, triptanes), anticoagulantes.',
 'Oral', TRUE, 'neurologicos', 'Tabletas 50 mg', 14.70),

('Alprazolam', 'alprazolam',
 'Benzodiacepina de acción corta para la ansiedad.',
 'Crisis de ansiedad y pánico, por periodos cortos y bajo prescripción.',
 'Alto riesgo de dependencia; nunca combinar con alcohol.',
 'Dosis mínima eficaz por el menor tiempo posible, según el médico.',
 'Somnolencia, mareo, problemas de memoria.',
 'Glaucoma de ángulo estrecho, insuficiencia respiratoria, embarazo.',
 'Alcohol, opioides y antihistamínicos sedantes potencian la depresión respiratoria.',
 'Oral', TRUE, 'neurologicos', 'Tabletas 0.5 mg', 7.60),

('Gabapentina', 'gabapentina',
 'Anticonvulsivante usado también para dolor neuropático.',
 'Dolor neuropático (ardor, hormigueo) y algunas epilepsias.',
 'Puede dar somnolencia al inicio; ajustar dosis gradualmente.',
 'Dosis progresiva según indicación; suele iniciarse con 300 mg por la noche.',
 'Somnolencia, mareo, hinchazón de tobillos.',
 'Alergia al principio activo; ajustar en insuficiencia renal.',
 'Antiácidos reducen su absorción; sedantes potencian la somnolencia.',
 'Oral', TRUE, 'neurologicos', 'Cápsulas 300 mg', 16.20),

('Sumatriptán', 'sumatriptán',
 'Triptán específico para las crisis de migraña.',
 'Ataques de migraña que no ceden con analgésicos comunes.',
 'Tomar al inicio del dolor; no usar para prevenir ni más de 2 dosis en 24 h.',
 '50-100 mg al inicio de la crisis; puede repetirse a las 2 horas (máx. 200 mg/día).',
 'Hormigueo, opresión leve en el pecho, somnolencia.',
 'Enfermedad coronaria, hipertensión no controlada, antecedente de infarto cerebral.',
 'No combinar con ergotamínicos ni IMAO; precaución con ISRS.',
 'Oral', TRUE, 'neurologicos', 'Tabletas 50 mg', 21.30),

-- Dermatológicos
('Ketoconazol crema', 'ketoconazol',
 'Antimicótico tópico de amplio espectro.',
 'Hongos de la piel, pitiriasis versicolor y dermatitis seborreica.',
 'Mantener la zona limpia y seca; completar el tratamiento.',
 'Aplicar 1-2 veces al día por 2-4 semanas.',
 'Irritación o picazón local leve.',
 'Alergia al ketoconazol.',
 'Pocas interacciones por vía tópica.',
 'Tópica', FALSE, 'dermatologicos', 'Crema 2% x 15 g', 9.40),

('Mupirocina', 'mupirocina',
 'Antibiótico tópico para infecciones bacterianas de la piel.',
 'Impétigo y heridas infectadas pequeñas.',
 'No usar en áreas extensas ni por más de 10 días.',
 'Aplicar una capa fina 3 veces al día por 5-10 días.',
 'Ardor o picazón leve al aplicar.',
 'Alergia a la mupirocina.',
 'Pocas interacciones por vía tópica.',
 'Tópica', TRUE, 'dermatologicos', 'Ungüento 2% x 15 g', 14.10),

('Aciclovir crema', 'aciclovir',
 'Antiviral tópico contra el virus del herpes.',
 'Herpes labial recurrente (fuegos).',
 'Iniciar al primer hormigueo; lavarse las manos tras aplicar.',
 'Aplicar 5 veces al día por 5 días.',
 'Ardor o sequedad local leve.',
 'Alergia al aciclovir.',
 'Pocas interacciones por vía tópica.',
 'Tópica', FALSE, 'dermatologicos', 'Crema 5% x 5 g', 10.80),

-- Antialérgicos
('Clorfenamina', 'clorfenamina maleato',
 'Antihistamínico clásico de primera generación.',
 'Alergias, rinitis y picazón; común en antigripales.',
 'Produce somnolencia: evitar conducir y combinar con alcohol.',
 'Adultos: 4 mg cada 6-8 horas según prospecto.',
 'Somnolencia marcada, boca seca, visión borrosa.',
 'Glaucoma, hipertrofia prostática, recién nacidos.',
 'Alcohol y sedantes potencian la somnolencia.',
 'Oral', FALSE, 'antialergicos', 'Tabletas 4 mg', 4.50),

('Difenhidramina', 'difenhidramina',
 'Antihistamínico sedante usado en alergias y para conciliar el sueño.',
 'Reacciones alérgicas, urticaria e insomnio ocasional.',
 'No usar de forma crónica para dormir; produce somnolencia intensa.',
 'Adultos: 25-50 mg cada 6-8 horas según prospecto.',
 'Somnolencia, mareo, boca seca.',
 'Glaucoma, asma agudo, hipertrofia prostática.',
 'Alcohol y otros sedantes potencian sus efectos.',
 'Oral', FALSE, 'antialergicos', 'Cápsulas 50 mg', 6.80),

-- Gastrointestinales
('Metoclopramida', 'metoclopramida',
 'Antiemético y procinético que acelera el vaciado gástrico.',
 'Náuseas, vómitos y digestión lenta según indicación.',
 'No usar más de 5 días seguidos; en jóvenes puede dar movimientos involuntarios.',
 'Adultos: 10 mg hasta 3 veces al día antes de las comidas.',
 'Somnolencia, inquietud, diarrea.',
 'Obstrucción intestinal, epilepsia, feocromocitoma.',
 'Sedantes y alcohol; antipsicóticos (suma efectos extrapiramidales).',
 'Oral', TRUE, 'gastrointestinales', 'Tabletas 10 mg', 5.90),

('Loperamida', 'loperamida',
 'Antidiarreico que disminuye los movimientos intestinales.',
 'Diarrea aguda sin fiebre ni sangre, junto con rehidratación.',
 'No usar si hay fiebre alta o sangre en las deposiciones; máximo 2 días sin consulta.',
 'Adultos: 4 mg al inicio y 2 mg tras cada deposición líquida (máx. 16 mg/día).',
 'Estreñimiento, gases, mareo leve.',
 'Diarrea con sangre o fiebre (disentería), colitis, menores de 2 años.',
 'Pocas interacciones relevantes en uso ocasional.',
 'Oral', FALSE, 'gastrointestinales', 'Cápsulas 2 mg', 7.20),

('Sales de rehidratación oral', 'electrolitos orales (fórmula OMS)',
 'Mezcla de glucosa y sales para reponer líquidos y electrolitos.',
 'Prevención y tratamiento de la deshidratación por diarrea o vómitos.',
 'Preparar con la cantidad exacta de agua hervida fría; desechar a las 24 horas.',
 'Tomar a sorbos frecuentes; en niños según peso e indicación.',
 'Muy bien toleradas; náuseas si se toma muy rápido.',
 'Obstrucción intestinal, vómitos incoercibles (requiere vía intravenosa).',
 'Sin interacciones relevantes.',
 'Oral', FALSE, 'gastrointestinales', 'Sobres para 1 litro', 2.50),

('Simeticona', 'simeticona',
 'Antiflatulento que rompe las burbujas de gas intestinal.',
 'Gases, hinchazón y cólicos por flatulencia.',
 'Si la hinchazón persiste varias semanas, consultar.',
 'Adultos: 40-125 mg después de las comidas y antes de dormir.',
 'Muy bien tolerada.',
 'Obstrucción intestinal conocida.',
 'Sin interacciones relevantes.',
 'Oral', FALSE, 'gastrointestinales', 'Cápsulas 125 mg', 8.60),

('Lactulosa', 'lactulosa',
 'Laxante osmótico suave de uso común.',
 'Estreñimiento crónico; también en problemas hepáticos según indicación.',
 'El efecto tarda 1-2 días; mantener buena hidratación.',
 'Adultos: 15-30 ml una vez al día, ajustando según respuesta.',
 'Gases e hinchazón los primeros días.',
 'Galactosemia, obstrucción intestinal.',
 'Antiácidos pueden reducir su efecto en dosis altas.',
 'Oral', FALSE, 'gastrointestinales', 'Jarabe 3.33 g/5 ml x 200 ml', 13.90),

-- Endocrinos
('Levotiroxina', 'levotiroxina sódica',
 'Hormona tiroidea sintética.',
 'Hipotiroidismo (tiroides lenta).',
 'Tomar en ayunas 30-60 minutos antes del desayuno, siempre a la misma hora.',
 'Dosis individualizada según análisis de TSH; control periódico.',
 'Si la dosis es alta: palpitaciones, insomnio, pérdida de peso.',
 'Hipertiroidismo no tratado, infarto reciente.',
 'Hierro, calcio y antiácidos reducen su absorción (separar 4 horas).',
 'Oral', TRUE, 'endocrinos', 'Tabletas 100 mcg', 11.80),

('Glibenclamida', 'glibenclamida',
 'Antidiabético oral que estimula la liberación de insulina.',
 'Diabetes tipo 2 cuando la metformina no es suficiente.',
 'Riesgo de hipoglucemia: no saltarse comidas; llevar siempre algo de azúcar.',
 'Según prescripción; habitualmente 5 mg antes del desayuno.',
 'Hipoglucemia (temblor, sudor frío, hambre), aumento de peso.',
 'Diabetes tipo 1, insuficiencia renal o hepática severa, embarazo.',
 'Alcohol y otros antidiabéticos potencian la hipoglucemia; corticoides la reducen.',
 'Oral', TRUE, 'endocrinos', 'Tabletas 5 mg', 6.40),

('Insulina NPH', 'insulina humana isófana',
 'Insulina de acción intermedia.',
 'Diabetes tipo 1 y tipo 2 que requiere insulina.',
 'Rotar sitios de inyección; conservar refrigerada; educar sobre hipoglucemia.',
 'Dosis individualizada por el médico según glucosa.',
 'Hipoglucemia, aumento de peso, reacción local en el sitio de inyección.',
 'Hipoglucemia activa.',
 'Alcohol, betabloqueadores (enmascaran hipoglucemia), corticoides suben la glucosa.',
 'Subcutánea', TRUE, 'endocrinos', 'Vial 100 UI/ml x 10 ml', 32.50),

-- Respiratorios
('Ambroxol', 'ambroxol',
 'Mucolítico que fluidifica las secreciones bronquiales.',
 'Tos con flema difícil de expulsar.',
 'Acompañar con abundante líquido; consultar si la tos dura más de 2 semanas.',
 'Adultos: 30 mg cada 8 horas según prospecto.',
 'Náuseas leves, sabor desagradable.',
 'Úlcera péptica activa; primer trimestre del embarazo salvo indicación.',
 'No combinar con antitusivos que bloqueen la expectoración.',
 'Oral', FALSE, 'respiratorios', 'Jarabe 30 mg/5 ml x 120 ml', 9.70),

('Dextrometorfano', 'dextrometorfano',
 'Antitusivo para la tos seca sin flema.',
 'Tos seca irritativa, especialmente nocturna.',
 'No usar en tos con flema; no exceder la dosis (puede causar mareo).',
 'Adultos: 15-30 mg cada 6-8 horas según prospecto.',
 'Somnolencia leve, mareo, náuseas.',
 'Uso con IMAO, asma agudo, tos productiva.',
 'IMAO y otros serotoninérgicos; alcohol potencia la somnolencia.',
 'Oral', FALSE, 'respiratorios', 'Jarabe 15 mg/5 ml x 120 ml', 8.90),

('Budesonida inhalada', 'budesonida',
 'Corticoide inhalado para el control del asma.',
 'Tratamiento de mantenimiento del asma y rinitis (no sirve para crisis).',
 'Enjuagarse la boca después de cada uso para evitar hongos orales.',
 'Según indicación; habitualmente 1-2 inhalaciones cada 12 horas.',
 'Ronquera, candidiasis oral si no se enjuaga.',
 'Infecciones respiratorias no tratadas; alergia al principio activo.',
 'Ketoconazol y otros inhibidores potentes aumentan sus niveles.',
 'Inhalatoria', TRUE, 'respiratorios', 'Inhalador 200 mcg/dosis', 38.40),

('Montelukast', 'montelukast',
 'Antileucotrieno para el control del asma y la rinitis alérgica.',
 'Asma leve persistente y rinitis alérgica, como tratamiento de mantenimiento.',
 'Informar cambios de ánimo o sueño; no sirve para crisis agudas.',
 'Adultos: 10 mg una vez al día por la noche.',
 'Dolor de cabeza, molestias digestivas; raramente alteraciones del ánimo.',
 'Alergia al principio activo.',
 'Fenobarbital y rifampicina reducen sus niveles.',
 'Oral', TRUE, 'respiratorios', 'Tabletas 10 mg', 17.60),

-- Suplementos
('Calcio + Vitamina D', 'carbonato de calcio con colecalciferol',
 'Suplemento combinado para la salud ósea.',
 'Prevención de osteoporosis y déficit de calcio.',
 'Tomar con las comidas; separar del hierro y la levotiroxina.',
 'Habitualmente 600 mg de calcio + 400 UI de vitamina D, 1-2 veces al día.',
 'Estreñimiento, gases.',
 'Hipercalcemia, cálculos renales de calcio.',
 'Reduce la absorción de hierro, levotiroxina y algunas quinolonas.',
 'Oral', FALSE, 'suplementos', 'Tabletas 600 mg + 400 UI', 12.30),

('Vitamina B12', 'cianocobalamina',
 'Vitamina esencial para los nervios y la formación de glóbulos rojos.',
 'Déficit de B12 (frecuente en veganos, adultos mayores y usuarios crónicos de omeprazol o metformina).',
 'El déficit prolongado puede dañar los nervios: no demorar el tratamiento indicado.',
 'Según indicación; habitualmente 1000 mcg al día o en esquemas semanales.',
 'Muy bien tolerada.',
 'Alergia al cobalto o a la cianocobalamina.',
 'Omeprazol y metformina reducen su absorción a largo plazo.',
 'Oral', FALSE, 'suplementos', 'Tabletas 1000 mcg', 9.10),

('Omega 3', 'ácidos grasos EPA y DHA',
 'Suplemento de aceite de pescado con ácidos grasos esenciales.',
 'Apoyo cardiovascular y de triglicéridos altos como complemento.',
 'Suspender unos días antes de cirugías (leve efecto anticoagulante).',
 'Habitualmente 1-2 g al día con las comidas.',
 'Sabor a pescado, molestias digestivas leves.',
 'Alergia al pescado o mariscos.',
 'Potencia levemente a los anticoagulantes en dosis altas.',
 'Oral', FALSE, 'suplementos', 'Cápsulas 1000 mg', 15.50);
ON CONFLICT (nombre_usuario) DO NOTHING;

-- ============================================================
-- Módulo Aprendizaje: 100 preguntas de quiz (medicina, dolencias
-- y medicamentos), cada una con 3 alternativas.
-- ============================================================
INSERT INTO pregunta_aprendizaje (id, enunciado, explicacion) VALUES
(1, '¿Para qué se usa principalmente el paracetamol?', 'El paracetamol (acetaminofén) se usa sobre todo para reducir fiebre y aliviar dolores leves a moderados.'),
(2, '¿Qué órgano puede dañarse si se excede la dosis de paracetamol?', 'En sobredosis, el paracetamol es tóxico para el hígado, sobre todo si se combina con alcohol.'),
(3, '¿Qué tipo de medicamento es el ibuprofeno?', 'El ibuprofeno es un antiinflamatorio no esteroideo (AINE) que alivia dolor, fiebre e inflamación.'),
(4, '¿Qué precaución es frecuente con los AINE como el ibuprofeno?', 'Pueden irritar el estómago; se recomienda tomarlos con alimento y evitar su uso prolongado sin control.'),
(5, '¿Qué tipo de medicamento es la amoxicilina?', 'La amoxicilina es un antibiótico betalactámico usado para tratar infecciones bacterianas.'),
(6, '¿Qué debe informar un paciente antes de recibir amoxicilina?', 'Es clave informar si existe alergia a penicilinas, ya que puede producir reacciones graves.'),
(7, '¿Para qué se usa el losartán?', 'El losartán es un antihipertensivo que ayuda a controlar la presión arterial elevada.'),
(8, '¿Para qué se usa principalmente la carbamazepina?', 'La carbamazepina es un antiepiléptico, también usado en algunos dolores neuropáticos.'),
(9, '¿Qué tipo de medicamento es la loratadina?', 'La loratadina es un antihistamínico que alivia síntomas de alergia como estornudos y picazón.'),
(10, '¿Para qué se usa el omeprazol?', 'El omeprazol reduce la producción de ácido del estómago; se usa en gastritis, acidez y reflujo.'),
(11, '¿Cuál es el medicamento inicial más usado en diabetes tipo 2?', 'La metformina es el antidiabético oral de primera línea en diabetes tipo 2.'),
(12, '¿Para qué sirve el salbutamol inhalado?', 'El salbutamol es un broncodilatador de acción rápida que alivia las crisis de asma.'),
(13, '¿Qué efecto adicional tiene la aspirina en dosis bajas?', 'En dosis bajas, la aspirina actúa como antiagregante plaquetario para prevención cardiovascular.'),
(14, '¿Por qué no se da aspirina a menores con infecciones virales?', 'Por el riesgo de síndrome de Reye, una complicación grave que afecta hígado y cerebro.'),
(15, '¿Para qué se usa el amlodipino?', 'El amlodipino es un antihipertensivo del grupo de los bloqueadores de canales de calcio.'),
(16, '¿Para qué se usa la atorvastatina?', 'La atorvastatina es una estatina que reduce el colesterol en sangre.'),
(17, '¿Qué tipo de medicamento es la cetirizina?', 'La cetirizina es un antihistamínico usado para aliviar síntomas de alergia.'),
(18, '¿Qué tipo de fármaco es la prednisona?', 'La prednisona es un corticoide con potente efecto antiinflamatorio e inmunosupresor.'),
(19, '¿Para qué enfermedad es esencial la insulina?', 'La insulina es esencial en la diabetes tipo 1 y en algunos casos de diabetes tipo 2.'),
(20, '¿A qué grupo pertenece el diazepam?', 'El diazepam es una benzodiacepina con efecto ansiolítico, sedante y relajante muscular.'),
(21, '¿Qué tipo de medicamento es la azitromicina?', 'La azitromicina es un antibiótico macrólido usado en infecciones respiratorias, entre otras.'),
(22, '¿Qué tipo de medicamento es el ciprofloxacino?', 'El ciprofloxacino es un antibiótico de la familia de las fluoroquinolonas.'),
(23, '¿Qué tipo de medicamento es el naproxeno?', 'El naproxeno es un AINE con efecto analgésico y antiinflamatorio de mayor duración.'),
(24, '¿Qué tipo de fármaco es la dexametasona?', 'La dexametasona es un corticoide potente usado en inflamaciones y alergias graves.'),
(25, '¿Para qué se usan medicamentos como la famotidina?', 'La famotidina reduce el ácido gástrico y se usa para acidez y úlceras.'),
(26, '¿Para qué sirven las sales de rehidratación oral?', 'Reponen agua y electrolitos perdidos, especialmente durante cuadros de diarrea.'),
(27, '¿Qué suplemento se usa para tratar la anemia ferropénica?', 'La anemia ferropénica se trata con suplementos de hierro, además de mejorar la dieta.'),
(28, '¿Qué suplemento se recomienda en el embarazo para prevenir defectos del tubo neural?', 'El ácido fólico se recomienda antes y durante el embarazo temprano.'),
(29, '¿Qué caracteriza a la clorfenamina frente a antihistamínicos modernos?', 'La clorfenamina es de primera generación y produce más somnolencia que las modernas.'),
(30, '¿Para qué se usa el metamizol?', 'El metamizol es un analgésico y antipirético usado para dolor y fiebre, bajo indicación.'),
(31, '¿Qué tipo de medicamento es el enalapril?', 'El enalapril es un antihipertensivo inhibidor de la enzima convertidora de angiotensina (IECA).'),
(32, '¿Qué efecto secundario clásico produce el enalapril en algunas personas?', 'El enalapril puede producir tos seca persistente; en ese caso se valora cambiar de fármaco.'),
(33, '¿Para qué se usa el albendazol?', 'El albendazol es un antiparasitario usado contra parásitos intestinales.'),
(34, '¿Para qué se usa el fluconazol?', 'El fluconazol es un antimicótico que trata infecciones por hongos.'),
(35, '¿Para qué se usa el aciclovir?', 'El aciclovir es un antiviral usado en infecciones por virus del herpes.'),
(36, '¿Para qué se usa la crema de hidrocortisona?', 'La hidrocortisona tópica alivia inflamación y picazón en afecciones de la piel.'),
(37, '¿Cuál es una presentación común del ibuprofeno?', 'El ibuprofeno suele encontrarse en comprimidos de 400 mg, aunque hay otras presentaciones.'),
(38, '¿Qué medicamento puede reducir el efecto del clopidogrel si se toman juntos?', 'El omeprazol puede reducir el efecto antiagregante del clopidogrel.'),
(39, '¿Qué bebida aumenta el riesgo de daño hepático combinada con paracetamol?', 'El alcohol aumenta el riesgo de toxicidad hepática del paracetamol.'),
(40, '¿Por qué vía se administra habitualmente el salbutamol en crisis de asma?', 'Se administra por vía inhalatoria para que actúe rápidamente en los bronquios.'),
(41, '¿Qué microorganismo causa la gripe?', 'La gripe es causada por el virus de la influenza; por eso los antibióticos no la curan.'),
(42, '¿Sirven los antibióticos para curar la gripe?', 'No: la gripe es viral y los antibióticos solo actúan contra bacterias.'),
(43, '¿Cómo suele ser el dolor de la migraña?', 'La migraña produce dolor pulsátil, a menudo en un lado de la cabeza, con náuseas y fotofobia.'),
(44, '¿Qué es la gastritis?', 'La gastritis es la inflamación de la mucosa que recubre el estómago.'),
(45, '¿Qué es la hipertensión arterial?', 'Es la elevación sostenida de la presión arterial por encima de los valores normales.'),
(46, '¿Por qué se llama a la hipertensión "el enemigo silencioso"?', 'Porque generalmente no produce síntomas, aunque dañe arterias y órganos con el tiempo.'),
(47, '¿Qué caracteriza a la diabetes tipo 2?', 'Niveles elevados de glucosa en sangre, generalmente por resistencia a la insulina.'),
(48, '¿Qué ocurre en las vías respiratorias durante una crisis de asma?', 'Los bronquios se inflaman y estrechan, dificultando el paso del aire.'),
(49, '¿Qué es la anemia?', 'Es la disminución de hemoglobina o glóbulos rojos; produce cansancio y palidez.'),
(50, '¿Qué es una alergia?', 'Es una reacción exagerada del sistema inmunitario frente a sustancias normalmente inofensivas.'),
(51, '¿A partir de qué temperatura corporal se considera fiebre en adultos?', 'Se considera fiebre a partir de 38 °C aproximadamente; entre 37.5 y 38 suele llamarse febrícula.'),
(52, '¿Cuál es un signo típico de deshidratación?', 'Boca seca, poca orina y mareo son signos frecuentes de deshidratación.'),
(53, '¿Qué es la artritis?', 'Es la inflamación de las articulaciones, que produce dolor, hinchazón y rigidez.'),
(54, '¿Qué parte del cuerpo afecta la otitis?', 'La otitis es la inflamación o infección del oído.'),
(55, '¿Qué es la conjuntivitis?', 'Es la inflamación de la conjuntiva del ojo; produce enrojecimiento y secreción.'),
(56, '¿Qué zona afecta la faringitis?', 'La faringitis afecta la garganta (faringe) y suele causar dolor al tragar.'),
(57, '¿Qué estructura se inflama en la bronquitis?', 'En la bronquitis se inflaman los bronquios, produciendo tos persistente.'),
(58, '¿Qué órgano afecta principalmente la neumonía?', 'La neumonía es una infección de los pulmones que puede ser grave.'),
(59, '¿Qué es el insomnio?', 'Es la dificultad para conciliar o mantener el sueño de forma adecuada.'),
(60, '¿Qué es el estreñimiento?', 'Es la dificultad o disminución de la frecuencia para evacuar el intestino.'),
(61, '¿Cuál es el principal riesgo de una diarrea aguda intensa?', 'La deshidratación es el principal riesgo, sobre todo en niños y adultos mayores.'),
(62, '¿Qué es la lumbalgia?', 'Es el dolor localizado en la zona baja de la espalda, muy frecuente y generalmente muscular.'),
(63, '¿Qué es la dermatitis?', 'Es la inflamación de la piel, con enrojecimiento, picazón o descamación.'),
(64, '¿Qué síntomas produce la rinitis alérgica?', 'Estornudos, picazón nasal, congestión y secreción acuosa son típicos de la rinitis alérgica.'),
(65, '¿Qué glándula funciona lentamente en el hipotiroidismo?', 'En el hipotiroidismo, la glándula tiroides produce menos hormonas de lo normal.'),
(66, '¿Qué caracteriza a la osteoporosis?', 'Los huesos pierden densidad y se vuelven frágiles, con mayor riesgo de fracturas.'),
(67, '¿Qué tipo de microorganismo causa la varicela?', 'La varicela es causada por un virus (varicela-zóster).'),
(68, '¿Qué es la caries dental?', 'Es el daño progresivo del esmalte del diente causado por ácidos de las bacterias.'),
(69, '¿Cómo suele sentirse la cefalea tensional?', 'Como una presión u opresión en ambos lados de la cabeza, ligada a estrés o tensión muscular.'),
(70, '¿Qué ocurre en el reflujo gastroesofágico?', 'El contenido ácido del estómago sube hacia el esófago y produce ardor o acidez.'),
(71, '¿Qué es un analgésico?', 'Un analgésico es un medicamento que alivia o reduce el dolor.'),
(72, '¿Qué es un antipirético?', 'Un antipirético es un medicamento que reduce la fiebre.'),
(73, '¿Contra qué actúan los antibióticos?', 'Los antibióticos actúan contra las bacterias; no sirven contra los virus.'),
(74, '¿Qué hace un antiinflamatorio?', 'Reduce la inflamación, y habitualmente también el dolor que la acompaña.'),
(75, '¿Para qué sirven los antihistamínicos?', 'Bloquean la histamina y alivian síntomas de alergia como picazón y estornudos.'),
(76, '¿Qué es un medicamento genérico?', 'Es el que contiene el mismo principio activo que el de marca, con calidad equivalente y menor precio.'),
(77, '¿Qué es la dosis de un medicamento?', 'Es la cantidad de medicamento que debe administrarse cada vez y con qué frecuencia.'),
(78, '¿Qué significa administrar un medicamento por vía oral?', 'Significa tomarlo por la boca, por ejemplo en comprimidos, cápsulas o jarabes.'),
(79, '¿Qué significa que un medicamento sea de uso tópico?', 'Que se aplica directamente sobre la piel o mucosas, como cremas o pomadas.'),
(80, '¿Qué es una contraindicación?', 'Es una situación en la que un medicamento NO debe usarse por el riesgo que implica.'),
(81, '¿Qué es un efecto secundario?', 'Es un efecto no deseado que puede aparecer junto al efecto buscado del medicamento.'),
(82, '¿Qué es una interacción medicamentosa?', 'Es cuando un medicamento modifica el efecto de otro al tomarse juntos.'),
(83, '¿Cuál es el principal riesgo de la automedicación?', 'Enmascarar enfermedades, sufrir efectos adversos o usar dosis incorrectas sin control profesional.'),
(84, '¿Por qué se debe completar un tratamiento antibiótico?', 'Abandonarlo antes favorece que las bacterias sobrevivan y generen resistencia.'),
(85, '¿Qué indica la fecha de vencimiento de un medicamento?', 'Hasta cuándo el fabricante garantiza su eficacia y seguridad; no debe usarse vencido.'),
(86, '¿Cuál es un lugar adecuado para guardar medicamentos?', 'Un lugar fresco, seco y fuera del alcance de los niños; el baño no es recomendable por la humedad.'),
(87, '¿Qué es una receta médica?', 'Es el documento con el que un profesional autorizado indica un medicamento y su pauta.'),
(88, '¿Qué es un placebo?', 'Es una sustancia sin principio activo, usada como comparación en estudios clínicos.'),
(89, '¿Para qué sirven las vacunas?', 'Entrenan al sistema inmunitario para prevenir enfermedades infecciosas.'),
(90, '¿Qué es un jarabe?', 'Es una forma farmacéutica líquida y azucarada, frecuente en presentaciones pediátricas.'),
(91, '¿Qué diferencia hay entre comprimido y cápsula?', 'El comprimido es polvo compactado; la cápsula tiene cubierta (a menudo de gelatina) con el fármaco dentro.'),
(92, '¿Qué significa administrar un medicamento por vía intravenosa?', 'Significa aplicarlo directamente en una vena, con efecto rápido; se usa en ámbito sanitario.'),
(93, 'Si un medicamento se toma "cada 8 horas", ¿cuántas veces al día se toma?', 'Cada 8 horas equivale a 3 tomas al día (24 ÷ 8 = 3).'),
(94, '¿Qué es el prospecto de un medicamento?', 'Es el documento informativo que acompaña al medicamento con sus indicaciones, dosis y precauciones.'),
(95, '¿Qué es una sobredosis?', 'Es la toma de una cantidad mayor a la recomendada, con riesgo de toxicidad grave.'),
(96, '¿Por qué se recomienda evitar el alcohol con muchos medicamentos?', 'El alcohol puede potenciar efectos sedantes o aumentar la toxicidad de varios fármacos.'),
(97, '¿Qué debe hacer una embarazada antes de tomar cualquier medicamento?', 'Consultar siempre con su médico, porque algunos fármacos pueden afectar al bebé.'),
(98, '¿Qué profesional está especializado en dispensar medicamentos y orientar sobre su uso?', 'El químico farmacéutico es el profesional que dispensa y orienta sobre los medicamentos.'),
(99, '¿Qué síntoma alivian los antitusivos?', 'Los antitusivos se usan para calmar la tos seca o irritativa.'),
(100, '¿Para qué se usan los laxantes?', 'Los laxantes ayudan a aliviar el estreñimiento facilitando la evacuación intestinal.');
ON CONFLICT (nombre_usuario) DO NOTHING;

-- Opciones (3 por pregunta; la posición de la correcta varía)
INSERT INTO opcion_aprendizaje (pregunta_id, texto_opcion, correcta) VALUES
(1, 'Reducir la presión arterial de forma permanente', FALSE),
(1, 'Aliviar fiebre y dolores leves a moderados', TRUE),
(1, 'Reemplazar antibióticos en infecciones bacterianas', FALSE),
(2, 'El hígado', TRUE),
(2, 'Los pulmones', FALSE),
(2, 'Los huesos', FALSE),
(3, 'Un antibiótico de amplio espectro', FALSE),
(3, 'Un corticoide', FALSE),
(3, 'Un antiinflamatorio no esteroideo (AINE)', TRUE),
(4, 'Pueden irritar el estómago; conviene tomarlos con alimento', TRUE),
(4, 'Se deben tomar siempre en ayunas para mayor efecto', FALSE),
(4, 'No tienen interacción con otros medicamentos', FALSE),
(5, 'Un antihistamínico', FALSE),
(5, 'Un antibiótico', TRUE),
(5, 'Un antihipertensivo', FALSE);
ON CONFLICT (nombre_usuario) DO NOTHING;

INSERT INTO opcion_aprendizaje (pregunta_id, texto_opcion, correcta) VALUES
(6, 'Si es alérgico a las penicilinas', TRUE),
(6, 'Si le gusta el sabor del jarabe', FALSE),
(6, 'Si practica deporte con frecuencia', FALSE),
(7, 'Para tratar infecciones urinarias', FALSE),
(7, 'Para controlar la hipertensión arterial', TRUE),
(7, 'Para aliviar la tos seca', FALSE),
(8, 'Tratar la epilepsia', TRUE),
(8, 'Bajar el colesterol', FALSE),
(8, 'Tratar el estreñimiento', FALSE),
(9, 'Un antihistamínico para alergias', TRUE),
(9, 'Un antibiótico macrólido', FALSE),
(9, 'Un analgésico opioide', FALSE),
(10, 'Aumentar el ácido del estómago', FALSE),
(10, 'Reducir la producción de ácido gástrico', TRUE),
(10, 'Estimular el apetito', FALSE);
ON CONFLICT (nombre_usuario) DO NOTHING;

INSERT INTO opcion_aprendizaje (pregunta_id, texto_opcion, correcta) VALUES
(11, 'La insulina inhalada', FALSE),
(11, 'La metformina', TRUE),
(11, 'El omeprazol', FALSE),
(12, 'Aliviar rápidamente las crisis de asma', TRUE),
(12, 'Curar la neumonía', FALSE),
(12, 'Reducir la acidez estomacal', FALSE),
(13, 'Antiagregante plaquetario (prevención cardiovascular)', TRUE),
(13, 'Antibiótico de refuerzo', FALSE),
(13, 'Broncodilatador', FALSE),
(14, 'Porque produce caries', FALSE),
(14, 'Por el riesgo de síndrome de Reye', TRUE),
(14, 'Porque no tiene efecto en menores', FALSE),
(15, 'Controlar la presión arterial', TRUE),
(15, 'Tratar infecciones por hongos', FALSE),
(15, 'Aliviar la picazón de la piel', FALSE);
ON CONFLICT (nombre_usuario) DO NOTHING;

INSERT INTO opcion_aprendizaje (pregunta_id, texto_opcion, correcta) VALUES
(16, 'Reducir el colesterol', TRUE),
(16, 'Subir las defensas', FALSE),
(16, 'Tratar la anemia', FALSE),
(17, 'Un antihistamínico', TRUE),
(17, 'Un antiparasitario', FALSE),
(17, 'Un anticoagulante', FALSE),
(18, 'Un corticoide antiinflamatorio', TRUE),
(18, 'Una vitamina', FALSE),
(18, 'Un antiviral', FALSE),
(19, 'La diabetes (especialmente tipo 1)', TRUE),
(19, 'La gastritis crónica', FALSE),
(19, 'La rinitis alérgica', FALSE),
(20, 'Las benzodiacepinas (ansiolíticos)', TRUE),
(20, 'Los antibióticos betalactámicos', FALSE),
(20, 'Las estatinas', FALSE);
ON CONFLICT (nombre_usuario) DO NOTHING;

INSERT INTO opcion_aprendizaje (pregunta_id, texto_opcion, correcta) VALUES
(21, 'Un antimicótico', FALSE),
(21, 'Un antibiótico macrólido', TRUE),
(21, 'Un antihipertensivo', FALSE),
(22, 'Un antibiótico (fluoroquinolona)', TRUE),
(22, 'Un laxante suave', FALSE),
(22, 'Un corticoide tópico', FALSE),
(23, 'Un AINE de acción prolongada', TRUE),
(23, 'Un antidepresivo', FALSE),
(23, 'Un protector gástrico', FALSE),
(24, 'Un corticoide potente', TRUE),
(24, 'Un suplemento de hierro', FALSE),
(24, 'Un antitusivo', FALSE),
(25, 'Para reducir el ácido del estómago', TRUE),
(25, 'Para dilatar los bronquios', FALSE),
(25, 'Para conciliar el sueño', FALSE);
ON CONFLICT (nombre_usuario) DO NOTHING;

INSERT INTO opcion_aprendizaje (pregunta_id, texto_opcion, correcta) VALUES
(26, 'Reponer agua y electrolitos en diarreas', TRUE),
(26, 'Aumentar la masa muscular', FALSE),
(26, 'Sustituir las comidas del día', FALSE),
(27, 'Suplementos de hierro', TRUE),
(27, 'Vitamina C en altas dosis únicamente', FALSE),
(27, 'Antibióticos de amplio espectro', FALSE),
(28, 'El ácido fólico', TRUE),
(28, 'El omeprazol', FALSE),
(28, 'La cafeína', FALSE),
(29, 'Produce más somnolencia', TRUE),
(29, 'No produce ningún efecto secundario', FALSE),
(29, 'Solo existe en forma inyectable', FALSE),
(30, 'Para aliviar dolor y fiebre', TRUE),
(30, 'Para tratar hongos en la piel', FALSE),
(30, 'Para reducir el colesterol', FALSE);
ON CONFLICT (nombre_usuario) DO NOTHING;

INSERT INTO opcion_aprendizaje (pregunta_id, texto_opcion, correcta) VALUES
(31, 'Un antihipertensivo (IECA)', TRUE),
(31, 'Un antidiabético oral', FALSE),
(31, 'Un antihistamínico', FALSE),
(32, 'Tos seca persistente', TRUE),
(32, 'Crecimiento del cabello', FALSE),
(32, 'Visión doble permanente', FALSE),
(33, 'Tratar parásitos intestinales', TRUE),
(33, 'Tratar la depresión', FALSE),
(33, 'Bajar la presión arterial', FALSE),
(34, 'Tratar infecciones por hongos', TRUE),
(34, 'Tratar la hipertensión', FALSE),
(34, 'Aliviar el dolor muscular', FALSE),
(35, 'Tratar infecciones por virus del herpes', TRUE),
(35, 'Tratar infecciones bacterianas urinarias', FALSE),
(35, 'Reducir la fiebre del dengue', FALSE);
ON CONFLICT (nombre_usuario) DO NOTHING;

INSERT INTO opcion_aprendizaje (pregunta_id, texto_opcion, correcta) VALUES
(36, 'Aliviar inflamación y picazón en la piel', TRUE),
(36, 'Blanquear los dientes', FALSE),
(36, 'Curar infecciones internas', FALSE),
(37, 'Comprimidos 400 mg', TRUE),
(37, 'Crema 1%', FALSE),
(37, 'Jarabe de insulina', FALSE),
(38, 'El omeprazol', TRUE),
(38, 'La vitamina C', FALSE),
(38, 'El paracetamol', FALSE),
(39, 'El alcohol', TRUE),
(39, 'El agua mineral', FALSE),
(39, 'El jugo de naranja', FALSE),
(40, 'Vía inhalatoria', TRUE),
(40, 'Vía intramuscular', FALSE),
(40, 'Vía tópica (crema)', FALSE);
ON CONFLICT (nombre_usuario) DO NOTHING;

INSERT INTO opcion_aprendizaje (pregunta_id, texto_opcion, correcta) VALUES
(41, 'Un virus (influenza)', TRUE),
(41, 'Una bacteria intestinal', FALSE),
(41, 'Un hongo ambiental', FALSE),
(42, 'No, porque la gripe es causada por un virus', TRUE),
(42, 'Sí, siempre que haya fiebre', FALSE),
(42, 'Sí, si se toman por más de 10 días', FALSE),
(43, 'Pulsátil y a menudo en un lado de la cabeza', TRUE),
(43, 'Solo en la planta de los pies', FALSE),
(43, 'Exclusivamente al masticar', FALSE),
(44, 'La inflamación de la mucosa del estómago', TRUE),
(44, 'La inflamación de los bronquios', FALSE),
(44, 'Una infección de la piel', FALSE),
(45, 'La elevación sostenida de la presión arterial', TRUE),
(45, 'El aumento del azúcar en sangre', FALSE),
(45, 'La disminución de glóbulos rojos', FALSE);
ON CONFLICT (nombre_usuario) DO NOTHING;

INSERT INTO opcion_aprendizaje (pregunta_id, texto_opcion, correcta) VALUES
(46, 'Porque generalmente no produce síntomas', TRUE),
(46, 'Porque solo aparece de noche', FALSE),
(46, 'Porque afecta únicamente a niños', FALSE),
(47, 'Glucosa elevada por resistencia a la insulina', TRUE),
(47, 'Falta de glóbulos blancos', FALSE),
(47, 'Exceso de calcio en los huesos', FALSE),
(48, 'Los bronquios se inflaman y se estrechan', TRUE),
(48, 'El corazón late más lento', FALSE),
(48, 'El estómago produce más ácido', FALSE),
(49, 'La disminución de hemoglobina o glóbulos rojos', TRUE),
(49, 'El aumento de plaquetas', FALSE),
(49, 'Una infección de la sangre', FALSE),
(50, 'Una reacción exagerada del sistema inmunitario', TRUE),
(50, 'Una infección causada por bacterias', FALSE),
(50, 'Una enfermedad hereditaria de la piel', FALSE);
ON CONFLICT (nombre_usuario) DO NOTHING;

INSERT INTO opcion_aprendizaje (pregunta_id, texto_opcion, correcta) VALUES
(51, 'A partir de 38 °C aproximadamente', TRUE),
(51, 'A partir de 36 °C', FALSE),
(51, 'Solo por encima de 40 °C', FALSE),
(52, 'Boca seca, poca orina y mareo', TRUE),
(52, 'Aumento de apetito', FALSE),
(52, 'Sudoración con buen estado general', FALSE),
(53, 'La inflamación de las articulaciones', TRUE),
(53, 'La inflamación del oído medio', FALSE),
(53, 'El endurecimiento de las arterias', FALSE),
(54, 'El oído', TRUE),
(54, 'El riñón', FALSE),
(54, 'La rodilla', FALSE),
(55, 'La inflamación de la conjuntiva del ojo', TRUE),
(55, 'Una infección de la garganta', FALSE),
(55, 'Una alergia alimentaria', FALSE);
ON CONFLICT (nombre_usuario) DO NOTHING;

INSERT INTO opcion_aprendizaje (pregunta_id, texto_opcion, correcta) VALUES
(56, 'La garganta (faringe)', TRUE),
(56, 'El intestino grueso', FALSE),
(56, 'La columna vertebral', FALSE),
(57, 'Los bronquios', TRUE),
(57, 'Los riñones', FALSE),
(57, 'Las articulaciones', FALSE),
(58, 'Los pulmones', TRUE),
(58, 'El hígado', FALSE),
(58, 'El páncreas', FALSE),
(59, 'La dificultad para conciliar o mantener el sueño', TRUE),
(59, 'El exceso de sueño durante el día', FALSE),
(59, 'Un trastorno de la memoria', FALSE),
(60, 'La dificultad para evacuar el intestino', TRUE),
(60, 'El aumento de deposiciones líquidas', FALSE),
(60, 'El dolor al orinar', FALSE);
ON CONFLICT (nombre_usuario) DO NOTHING;

INSERT INTO opcion_aprendizaje (pregunta_id, texto_opcion, correcta) VALUES
(61, 'La deshidratación', TRUE),
(61, 'El aumento de peso', FALSE),
(61, 'La pérdida de cabello', FALSE),
(62, 'El dolor en la zona baja de la espalda', TRUE),
(62, 'El dolor de cabeza tensional', FALSE),
(62, 'La inflamación del hombro', FALSE),
(63, 'La inflamación de la piel', TRUE),
(63, 'La infección de las uñas', FALSE),
(63, 'La caída del cabello', FALSE),
(64, 'Estornudos, picazón y congestión nasal', TRUE),
(64, 'Dolor en las articulaciones', FALSE),
(64, 'Visión borrosa y mareos', FALSE),
(65, 'La tiroides', TRUE),
(65, 'La hipófisis solamente', FALSE),
(65, 'Las glándulas sudoríparas', FALSE);

INSERT INTO opcion_aprendizaje (pregunta_id, texto_opcion, correcta) VALUES
(66, 'Huesos frágiles con riesgo de fracturas', TRUE),
(66, 'Músculos inflamados de forma crónica', FALSE),
(66, 'Exceso de calcio en la sangre', FALSE),
(67, 'Un virus (varicela-zóster)', TRUE),
(67, 'Una bacteria de la piel', FALSE),
(67, 'Un parásito intestinal', FALSE),
(68, 'El daño del esmalte por ácidos bacterianos', TRUE),
(68, 'Una mancha por café', FALSE),
(68, 'La inflamación de la lengua', FALSE),
(69, 'Como presión u opresión en ambos lados de la cabeza', TRUE),
(69, 'Como punzadas en el abdomen', FALSE),
(69, 'Como hormigueo en las manos', FALSE),
(70, 'El ácido del estómago sube hacia el esófago', TRUE),
(70, 'El intestino absorbe demasiada agua', FALSE),
(70, 'La vesícula produce más bilis', FALSE);
ON CONFLICT (nombre_usuario) DO NOTHING;

INSERT INTO opcion_aprendizaje (pregunta_id, texto_opcion, correcta) VALUES
(71, 'Un medicamento que alivia el dolor', TRUE),
(71, 'Un medicamento que produce sueño', FALSE),
(71, 'Un medicamento contra las bacterias', FALSE),
(72, 'Un medicamento que reduce la fiebre', TRUE),
(72, 'Un medicamento que sube las defensas', FALSE),
(72, 'Un medicamento para la tos', FALSE),
(73, 'Contra las bacterias', TRUE),
(73, 'Contra los virus', FALSE),
(73, 'Contra el dolor crónico', FALSE),
(74, 'Reduce la inflamación y el dolor asociado', TRUE),
(74, 'Aumenta la presión arterial', FALSE),
(74, 'Estimula el sistema inmune', FALSE),
(75, 'Alivian síntomas de alergia bloqueando la histamina', TRUE),
(75, 'Curan las infecciones virales', FALSE),
(75, 'Fortalecen los huesos', FALSE);
ON CONFLICT (nombre_usuario) DO NOTHING;

INSERT INTO opcion_aprendizaje (pregunta_id, texto_opcion, correcta) VALUES
(76, 'El que tiene el mismo principio activo que el de marca', TRUE),
(76, 'Un medicamento de menor calidad', FALSE),
(76, 'Un medicamento sin principio activo', FALSE),
(77, 'La cantidad y frecuencia con que debe tomarse', TRUE),
(77, 'El precio del medicamento', FALSE),
(77, 'El color del envase', FALSE),
(78, 'Tomarlo por la boca', TRUE),
(78, 'Aplicarlo sobre la piel', FALSE),
(78, 'Inyectarlo en el músculo', FALSE),
(79, 'Que se aplica sobre la piel o mucosas', TRUE),
(79, 'Que se toma con las comidas', FALSE),
(79, 'Que solo se vende con receta', FALSE),
(80, 'Una situación en la que el medicamento no debe usarse', TRUE),
(80, 'Una indicación de uso frecuente', FALSE),
(80, 'Un efecto positivo adicional', FALSE);
ON CONFLICT (nombre_usuario) DO NOTHING;

INSERT INTO opcion_aprendizaje (pregunta_id, texto_opcion, correcta) VALUES
(81, 'Un efecto no deseado que acompaña al efecto buscado', TRUE),
(81, 'El efecto principal del medicamento', FALSE),
(81, 'Una alergia obligatoria en todos los pacientes', FALSE),
(82, 'Cuando un medicamento modifica el efecto de otro', TRUE),
(82, 'Cuando dos medicamentos tienen el mismo color', FALSE),
(82, 'Cuando un medicamento caduca antes que otro', FALSE),
(83, 'Efectos adversos y enmascarar enfermedades sin control profesional', TRUE),
(83, 'Ahorrar tiempo en la farmacia', FALSE),
(83, 'Ningún riesgo si el medicamento es conocido', FALSE),
(84, 'Para evitar que las bacterias generen resistencia', TRUE),
(84, 'Para gastar todo el envase comprado', FALSE),
(84, 'Porque los antibióticos abren el apetito', FALSE),
(85, 'Hasta cuándo se garantiza su eficacia y seguridad', TRUE),
(85, 'La fecha en que fue fabricado', FALSE),
(85, 'El día recomendado para empezar a tomarlo', FALSE);
ON CONFLICT (nombre_usuario) DO NOTHING;

INSERT INTO opcion_aprendizaje (pregunta_id, texto_opcion, correcta) VALUES
(86, 'Un lugar fresco, seco y fuera del alcance de los niños', TRUE),
(86, 'El botiquín del baño, por la humedad', FALSE),
(86, 'Cerca de la cocina, por comodidad', FALSE),
(87, 'El documento con el que un profesional indica un medicamento', TRUE),
(87, 'Una lista de precios de la farmacia', FALSE),
(87, 'Un certificado de vacunación', FALSE),
(88, 'Una sustancia sin principio activo usada en estudios', TRUE),
(88, 'Un medicamento de doble potencia', FALSE),
(88, 'Una vitamina de alta concentración', FALSE),
(89, 'Prevenir enfermedades infecciosas entrenando al sistema inmune', TRUE),
(89, 'Curar infecciones ya establecidas', FALSE),
(89, 'Sustituir la alimentación saludable', FALSE),
(90, 'Una forma farmacéutica líquida y azucarada', TRUE),
(90, 'Una pastilla efervescente', FALSE),
(90, 'Una inyección de acción lenta', FALSE);
ON CONFLICT (nombre_usuario) DO NOTHING;

INSERT INTO opcion_aprendizaje (pregunta_id, texto_opcion, correcta) VALUES
(91, 'El comprimido es polvo compactado; la cápsula tiene cubierta con el fármaco dentro', TRUE),
(91, 'Son exactamente lo mismo', FALSE),
(91, 'La cápsula siempre es más potente', FALSE),
(92, 'Aplicarlo directamente en una vena', TRUE),
(92, 'Tomarlo disuelto en agua', FALSE),
(92, 'Aplicarlo debajo de la lengua', FALSE),
(93, '3 veces al día', TRUE),
(93, '8 veces al día', FALSE),
(93, '1 vez al día', FALSE),
(94, 'El documento informativo que acompaña al medicamento', TRUE),
(94, 'La etiqueta con el precio', FALSE),
(94, 'La caja exterior del producto', FALSE),
(95, 'Tomar una cantidad mayor a la recomendada, con riesgo de toxicidad', TRUE),
(95, 'Olvidar una dosis del tratamiento', FALSE),
(95, 'Cambiar de marca de medicamento', FALSE);
ON CONFLICT (nombre_usuario) DO NOTHING;

INSERT INTO opcion_aprendizaje (pregunta_id, texto_opcion, correcta) VALUES
(96, 'Puede potenciar efectos sedantes o aumentar la toxicidad', TRUE),
(96, 'El alcohol mejora la absorción de todos los fármacos', FALSE),
(96, 'No hay ninguna razón, es solo costumbre', FALSE),
(97, 'Consultar siempre con su médico antes de tomarlo', TRUE),
(97, 'Tomar la mitad de la dosis por seguridad', FALSE),
(97, 'Evitar solo los medicamentos inyectables', FALSE),
(98, 'El químico farmacéutico', TRUE),
(98, 'El nutricionista', FALSE),
(98, 'El técnico de laboratorio', FALSE),
(99, 'La tos seca o irritativa', TRUE),
(99, 'El dolor de espalda', FALSE),
(99, 'La picazón de ojos', FALSE),
(100, 'Aliviar el estreñimiento', TRUE),
(100, 'Detener la diarrea', FALSE),
(100, 'Reducir la fiebre', FALSE);
ON CONFLICT (nombre_usuario) DO NOTHING;

-- ============================================================
-- Módulo Aprendizaje: párrafos del juego "Completar palabras"
-- (las palabras a completar van entre [corchetes])
-- ============================================================
INSERT INTO parrafo_juego (titulo, contenido) VALUES
('El paracetamol',
 'El [paracetamol] es un analgésico que alivia el [dolor] y reduce la [fiebre]. Se administra por vía [oral] y nunca debe excederse la [dosis] máxima indicada en el prospecto, porque puede dañar el hígado.'),
('Los antibióticos',
 'Los [antibióticos] son medicamentos que combaten infecciones causadas por [bacterias]. Es muy importante completar todo el [tratamiento] indicado por el médico, porque abandonarlo antes favorece la [resistencia] bacteriana.'),
('El asma',
 'El [asma] es una enfermedad crónica que afecta a las vías [respiratorias]. Durante una crisis se utiliza [salbutamol] inhalado, que actúa abriendo los [bronquios] y facilitando la respiración.'),
('La hipertensión',
 'La [hipertensión] arterial es la elevación sostenida de la [presión] en las arterias. Suele no presentar [síntomas], por eso se le llama el enemigo silencioso. El [losartán] es uno de los medicamentos usados para controlarla.'),
('La diabetes',
 'La [diabetes] tipo 2 se caracteriza por niveles altos de [glucosa] en la sangre. La [metformina] es el medicamento inicial más usado, siempre acompañado de una dieta saludable y [ejercicio] regular.'),
('La gastritis',
 'La [gastritis] es la inflamación de la mucosa del [estómago]. El [omeprazol] ayuda a aliviar las molestias porque reduce la producción de [ácido] gástrico.'),
('Las alergias',
 'Una [alergia] es una reacción exagerada del sistema [inmunitario] frente a sustancias normalmente inofensivas. Los [antihistamínicos], como la loratadina, alivian los [estornudos] y la picazón.'),
('La gripe',
 'La [gripe] es una infección causada por un [virus], por lo que los antibióticos [no] son útiles contra ella. El tratamiento se basa en reposo, [hidratación] y medicamentos para aliviar los síntomas.'),
('La anemia',
 'La [anemia] ferropénica se produce por falta de [hierro] y provoca cansancio y [palidez]. Se trata con suplementos y con alimentos ricos en este mineral, como las carnes rojas y las [menestras].'),
('La automedicación',
 'La [automedicación] sin control profesional es riesgosa: puede enmascarar [enfermedades], provocar efectos [adversos] e interacciones peligrosas. Ante cualquier duda, consulta al médico o al [farmacéutico].');
ON CONFLICT (nombre_usuario) DO NOTHING;

-- ============================================================
-- Módulo Aprendizaje: "Tutorial para ser médico" (casos clínicos)
-- Cada caso tiene 3 diagnósticos posibles y 3 justificaciones.
-- ============================================================
INSERT INTO caso_clinico (id, titulo, perfil, explicacion) VALUES
(1, 'La garganta de Valeria',
 'Paciente mujer de 24 años, tipo de sangre O+. Acude con 2 días de fiebre de 38.5 °C, dolor de garganta intenso al tragar y ganglios inflamados en el cuello. No tiene tos ni congestión nasal.',
 'El dolor al tragar con fiebre y ganglios cervicales inflamados orienta a una faringitis. La ausencia de tos hace menos probable un cuadro gripal común.'),
(2, 'El chequeo de don Ricardo',
 'Paciente varón de 55 años, fumador, tipo de sangre A+. En tres controles distintos su presión arterial marca 160/100 mmHg. Se siente completamente bien y no entiende por qué lo citan de nuevo.',
 'Cifras repetidas de 160/100 mmHg confirman hipertensión arterial. Es típicamente silenciosa: sentirse bien no descarta el daño progresivo a arterias, corazón y riñones.'),
(3, 'El dolor de cabeza de Camila',
 'Paciente mujer de 30 años, tipo de sangre B+. Refiere episodios de dolor de cabeza pulsátil en el lado derecho, con náuseas, que empeoran con la luz y el ruido. Debe encerrarse en su cuarto a oscuras hasta que pasan.',
 'El dolor pulsátil unilateral con náuseas, fotofobia y fonofobia es el cuadro clásico de la migraña.'),
(4, 'La sed de don Manuel',
 'Paciente varón de 45 años con sobrepeso, tipo de sangre O−. Desde hace meses tiene mucha sed, orina con mucha frecuencia y se siente cansado. Una glucosa en ayunas salió en 180 mg/dl.',
 'Sed excesiva, orina frecuente, cansancio y glucosa en ayunas mayor a 126 mg/dl son criterios típicos de diabetes tipo 2, más aún con sobrepeso.'),
(5, 'La tos nocturna de Mateo',
 'Paciente niño de 8 años, tipo de sangre A−. Sus padres cuentan que tose seco casi todas las noches y que cuando corre en el colegio le silba el pecho y se agita más que sus compañeros.',
 'Tos seca nocturna y silbidos con el ejercicio en un niño son muy sugestivos de asma: las vías respiratorias se inflaman y se estrechan.'),
(6, 'Las agruras de la señora Rosa',
 'Paciente mujer de 35 años, tipo de sangre AB+. Siente ardor que sube del estómago al pecho después de cenas abundantes, y empeora cuando se acuesta. A veces nota sabor amargo en la boca.',
 'El ardor ascendente que empeora al acostarse y la regurgitación con sabor amargo son típicos del reflujo gastroesofágico.'),
(7, 'Los estornudos de Diego',
 'Paciente varón de 19 años, tipo de sangre O+. Cada vez que limpia el polvo de su cuarto presenta estornudos en salva, picazón de nariz y ojos llorosos. Le pasa igual en primavera.',
 'Estornudos, picazón nasal y ojos llorosos desencadenados por polvo o polen indican rinitis alérgica, una reacción del sistema inmunitario.'),
(8, 'El malestar de Jorge',
 'Paciente varón de 28 años, tipo de sangre B−. Ayer comió en un puesto callejero y hoy presenta deposiciones líquidas frecuentes, cólicos, boca seca y algo de mareo al pararse.',
 'Deposiciones líquidas tras una comida sospechosa indican diarrea aguda. La boca seca y el mareo al pararse son signos de deshidratación: lo primero es rehidratar.'),
(9, 'El cansancio de Lucía',
 'Paciente mujer de 40 años, tipo de sangre A+. Refiere cansancio desde hace meses, se ve pálida, sus uñas se quiebran con facilidad y sus menstruaciones son muy abundantes.',
 'Cansancio, palidez y uñas frágiles en una mujer con menstruaciones abundantes sugieren anemia ferropénica: se pierde más hierro del que se repone.'),
(10, 'Las rodillas de don Alberto',
 'Paciente varón de 60 años, tipo de sangre O+. Tiene dolor en ambas rodillas con rigidez al levantarse por las mañanas que mejora al moverse; a veces las nota hinchadas.',
 'Dolor articular con rigidez matutina e hinchazón en una persona mayor orienta a artritis: inflamación de las articulaciones.');
ON CONFLICT (nombre_usuario) DO NOTHING;

-- Opciones de diagnóstico (3 por caso)
INSERT INTO opcion_caso_clinico (caso_id, tipo, texto, correcta) VALUES
(1, 'DIAGNOSTICO', 'Faringitis', TRUE),
(1, 'DIAGNOSTICO', 'Gastritis', FALSE),
(1, 'DIAGNOSTICO', 'Rinitis alérgica', FALSE),
(2, 'DIAGNOSTICO', 'Hipertensión arterial', TRUE),
(2, 'DIAGNOSTICO', 'Anemia ferropénica', FALSE),
(2, 'DIAGNOSTICO', 'Migraña', FALSE),
(3, 'DIAGNOSTICO', 'Migraña', TRUE),
(3, 'DIAGNOSTICO', 'Cefalea tensional', FALSE),
(3, 'DIAGNOSTICO', 'Conjuntivitis', FALSE),
(4, 'DIAGNOSTICO', 'Diabetes tipo 2', TRUE),
(4, 'DIAGNOSTICO', 'Infección urinaria', FALSE),
(4, 'DIAGNOSTICO', 'Hipertiroidismo', FALSE),
(5, 'DIAGNOSTICO', 'Asma', TRUE),
(5, 'DIAGNOSTICO', 'Neumonía', FALSE),
(5, 'DIAGNOSTICO', 'Faringitis', FALSE),
(6, 'DIAGNOSTICO', 'Reflujo gastroesofágico', TRUE),
(6, 'DIAGNOSTICO', 'Asma', FALSE),
(6, 'DIAGNOSTICO', 'Artritis', FALSE),
(7, 'DIAGNOSTICO', 'Rinitis alérgica', TRUE),
(7, 'DIAGNOSTICO', 'Gripe', FALSE),
(7, 'DIAGNOSTICO', 'Bronquitis', FALSE),
(8, 'DIAGNOSTICO', 'Diarrea aguda con deshidratación', TRUE),
(8, 'DIAGNOSTICO', 'Gastritis crónica', FALSE),
(8, 'DIAGNOSTICO', 'Apendicitis', FALSE),
(9, 'DIAGNOSTICO', 'Anemia ferropénica', TRUE),
(9, 'DIAGNOSTICO', 'Diabetes tipo 2', FALSE),
(9, 'DIAGNOSTICO', 'Hipotiroidismo', FALSE),
(10, 'DIAGNOSTICO', 'Artritis', TRUE),
(10, 'DIAGNOSTICO', 'Lumbalgia', FALSE),
(10, 'DIAGNOSTICO', 'Osteoporosis', FALSE);
ON CONFLICT (nombre_usuario) DO NOTHING;

-- Opciones de justificación (3 por caso)
INSERT INTO opcion_caso_clinico (caso_id, tipo, texto, correcta) VALUES
(1, 'JUSTIFICACION', 'Tiene dolor al tragar, fiebre y ganglios inflamados, sin tos ni congestión', TRUE),
(1, 'JUSTIFICACION', 'Presenta ardor estomacal después de las comidas', FALSE),
(1, 'JUSTIFICACION', 'Tiene estornudos y picazón nasal por alérgenos', FALSE),
(2, 'JUSTIFICACION', 'Su presión salió elevada (160/100) en varias tomas, aunque no tenga síntomas', TRUE),
(2, 'JUSTIFICACION', 'Se ve pálido y refiere mucho cansancio', FALSE),
(2, 'JUSTIFICACION', 'Tiene dolor de cabeza pulsátil con náuseas', FALSE),
(3, 'JUSTIFICACION', 'El dolor es pulsátil, en un solo lado, con náuseas y molestia a la luz', TRUE),
(3, 'JUSTIFICACION', 'El dolor es como una banda que aprieta ambos lados, sin náuseas', FALSE),
(3, 'JUSTIFICACION', 'Tiene el ojo rojo con lagrimeo y secreción', FALSE),
(4, 'JUSTIFICACION', 'Tiene sed excesiva, orina frecuente y una glucosa en ayunas de 180 mg/dl', TRUE),
(4, 'JUSTIFICACION', 'Presenta ardor al orinar con fiebre', FALSE),
(4, 'JUSTIFICACION', 'Tiene palpitaciones y pérdida de peso con mucho apetito', FALSE),
(5, 'JUSTIFICACION', 'Tose seco de noche y el pecho le silba al hacer ejercicio', TRUE),
(5, 'JUSTIFICACION', 'Tiene fiebre alta con dolor de pecho y flema oxidada', FALSE),
(5, 'JUSTIFICACION', 'Le duele la garganta al tragar con ganglios inflamados', FALSE),
(6, 'JUSTIFICACION', 'El ardor sube hacia el pecho, empeora acostada y deja sabor amargo', TRUE),
(6, 'JUSTIFICACION', 'Le silba el pecho y le falta el aire al hacer esfuerzos', FALSE),
(6, 'JUSTIFICACION', 'Tiene las articulaciones rígidas por las mañanas', FALSE),
(7, 'JUSTIFICACION', 'Los estornudos y la picazón aparecen al exponerse a polvo o polen', TRUE),
(7, 'JUSTIFICACION', 'Tiene fiebre, dolor de cuerpo y malestar general', FALSE),
(7, 'JUSTIFICACION', 'Presenta tos con flema desde hace tres semanas', FALSE),
(8, 'JUSTIFICACION', 'Tras una comida sospechosa tiene deposiciones líquidas y signos de deshidratación', TRUE),
(8, 'JUSTIFICACION', 'El dolor empezó alrededor del ombligo y se movió a la fosa iliaca derecha con fiebre', FALSE),
(8, 'JUSTIFICACION', 'Tiene ardor estomacal crónico que mejora al comer', FALSE),
(9, 'JUSTIFICACION', 'Está pálida, cansada, con uñas frágiles y pierde hierro por menstruaciones abundantes', TRUE),
(9, 'JUSTIFICACION', 'Tiene mucha sed y orina con frecuencia', FALSE),
(9, 'JUSTIFICACION', 'Sube de peso y siente frío todo el tiempo, con piel seca', FALSE),
(10, 'JUSTIFICACION', 'Tiene dolor e hinchazón articular con rigidez matutina que mejora al moverse', TRUE),
(10, 'JUSTIFICACION', 'El dolor es lumbar y aumenta con malas posturas', FALSE),
(10, 'JUSTIFICACION', 'Sufrió una fractura espontánea por huesos frágiles', FALSE);
ON CONFLICT (nombre_usuario) DO NOTHING;

-- ============================================================
-- Actividad de ejemplo en los minijuegos (para el Panel)
-- usuario 1 = admin, usuario 2 = estudiante
-- ============================================================
INSERT INTO actividad_aprendizaje (usuario_id, juego, total, aciertos, fecha) VALUES
(2, 'QUIZ', 10, 5, CURRENT_TIMESTAMP - INTERVAL '6 days'),
(2, 'COMPLETAR', 4, 4, CURRENT_TIMESTAMP - INTERVAL '5 days'),
(2, 'QUIZ', 10, 7, CURRENT_TIMESTAMP - INTERVAL '4 days'),
(2, 'CASOS', 2, 1, CURRENT_TIMESTAMP - INTERVAL '3 days'),
(2, 'COMPLETAR', 5, 5, CURRENT_TIMESTAMP - INTERVAL '2 days'),
(2, 'QUIZ', 10, 8, CURRENT_TIMESTAMP - INTERVAL '1 day'),
(2, 'CASOS', 2, 2, CURRENT_TIMESTAMP),
(1, 'QUIZ', 10, 9, CURRENT_TIMESTAMP - INTERVAL '1 day'),
(1, 'CASOS', 2, 2, CURRENT_TIMESTAMP);
ON CONFLICT (nombre_usuario) DO NOTHING;