-- PHARMLY: esquema en español (H2). Las entidades JPA mapean estos nombres físicos.
CREATE TABLE IF NOT EXISTS medicamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    nombre_generico VARCHAR(255),
    descripcion VARCHAR(4000),
    uso_comun VARCHAR(4000),
    precauciones VARCHAR(4000),
    orientacion_dosis VARCHAR(2000),
    efectos_secundarios VARCHAR(4000),
    categoria VARCHAR(80),
    presentacion VARCHAR(255),
    precio DECIMAL(10, 2)
);

CREATE TABLE IF NOT EXISTS pregunta_aprendizaje (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enunciado VARCHAR(2000) NOT NULL,
    explicacion VARCHAR(4000)
);

CREATE TABLE IF NOT EXISTS opcion_aprendizaje (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pregunta_id BIGINT NOT NULL,
    texto_opcion VARCHAR(1000) NOT NULL,
    correcta BOOLEAN NOT NULL,
    CONSTRAINT fk_opcion_pregunta FOREIGN KEY (pregunta_id) REFERENCES pregunta_aprendizaje(id)
);
