-- PHARMLY: esquema en español (H2). Las entidades JPA mapean estos nombres físicos.
-- Basado en el diagrama ER del equipo (USUARIO, PREGUNTAS/RESPUESTAS, CATEGORIA_MEDICINA,
-- MEDICAMENTOS, CATEGORIA_DOLENCIAS, DOLENCIAS), normalizado y ampliado.

-- ===== Usuarios (login y roles) =====
CREATE TABLE IF NOT EXISTS usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR(80) NOT NULL UNIQUE,
    contrasenia VARCHAR(255) NOT NULL,
    tipo VARCHAR(30) NOT NULL, -- USUARIO_GENERAL | ESTUDIANTE | ADMIN
    nombre VARCHAR(255) NOT NULL,
    correo VARCHAR(255)
);

-- ===== Catálogo de categorías de medicamentos =====
CREATE TABLE IF NOT EXISTS categoria_medicamento (
    clave VARCHAR(80) PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL
);

-- ===== Dolencias y sus categorías =====
CREATE TABLE IF NOT EXISTS categoria_dolencia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS dolencia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    categoria_id BIGINT,
    descripcion VARCHAR(4000),
    CONSTRAINT fk_dolencia_categoria FOREIGN KEY (categoria_id) REFERENCES categoria_dolencia(id)
);

-- ===== Medicamentos (ficha detallada) =====
CREATE TABLE IF NOT EXISTS medicamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    nombre_generico VARCHAR(255),
    descripcion VARCHAR(4000),
    uso_comun VARCHAR(4000),
    precauciones VARCHAR(4000),
    orientacion_dosis VARCHAR(2000),
    efectos_secundarios VARCHAR(4000),
    contraindicaciones VARCHAR(4000),
    interacciones VARCHAR(4000),
    via_administracion VARCHAR(255),
    requiere_receta BOOLEAN DEFAULT FALSE,
    categoria VARCHAR(80),
    presentacion VARCHAR(255),
    precio DECIMAL(10, 2),
    CONSTRAINT fk_medicamento_categoria FOREIGN KEY (categoria) REFERENCES categoria_medicamento(clave)
);

-- ===== Módulo Aprendizaje: quiz (preguntas y respuestas/opciones) =====
CREATE TABLE IF NOT EXISTS pregunta_aprendizaje (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enunciado VARCHAR(2000) NOT NULL,
    explicacion VARCHAR(4000)
);

CREATE TABLE IF NOT EXISTS opcion_aprendizaje (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pregunta_id BIGINT NOT NULL,
    texto_opcion VARCHAR(1000) NOT NULL,
    correcta BOOLEAN NOT NULL,
    CONSTRAINT fk_opcion_pregunta FOREIGN KEY (pregunta_id) REFERENCES pregunta_aprendizaje(id)
);

-- ===== Módulo Aprendizaje: juego de completar palabras =====
-- Las palabras a completar van entre [corchetes] dentro del contenido.
CREATE TABLE IF NOT EXISTS parrafo_juego (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255),
    contenido VARCHAR(4000) NOT NULL
);
